### ISSUE TITLE
Improve this page button in online manual

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#1]
I saw an interesting approach using a Sphinx page, it has a `Improve this page` button, that creates an issue with the text, and the person can edit the text and modify and also point typos and stuff.

[here is the link for the code](https://github.com/Unidata/MetPy/blob/master/docs/_templates/breadcrumbs.html)

[here is it in the docs, top right corner](https://unidata.github.io/MetPy/latest/examples/index.html)

**Comment by tzachshabtay** [comment]
Hmmm, personally I prefer the previously discussed approach, where the "improve this page" link brings you to the "fork this page" button on github so you can make your edits and do a PR -> less work for both the maintainers and the "improver".

**Comment by ericoporto** [comment]
I do too, but the wiki doesn't support the PR flow through the github interface. :/

**Comment by ivan-mogilko** [comment]
How do I make wiki public? I was looking for this feature a while ago for the main repository too.

**Comment by ivan-mogilko** [comment]
> and make the wiki public so that everybody can contribute

What do you mean by "public", as in everyone can edit directly?

**Comment by tzachshabtay** [comment]
Yes.

**Comment by ivan-mogilko** [comment]
I think I've found the option in settings which allows that, but I am a bit worried about how the dev team will keep any control over the contents of the manual in such case?

**Comment by tzachshabtay** [comment]
Each wiki page seems to have revisions, so it should be possible to revert if something like that happens. Obviously if there are malicious users which keep corrupting the wiki then we'll need to re-evaluate, but I doubt that will happen -> currently we have the opposite problem, right? where nobody contributes, so it makes sense to me that we want to make the process as easy as possible until proven otherwise.

**Comment by ivan-mogilko** [comment]
Ok, I opened wiki for public.

**Comment by morganwillcock** [comment]
I guess the only issue might be, if running an offline copy of the html build, all of the other links would work offline but these would not. Maybe styling could be slightly different for online links vs local ones?

I think the idea of linking to where you would edit the page is a good one.

**Comment by ericoporto** [comment]
Hey, since this is working, I am closing this issue. Improvements on this idea can be discussed on a new issue.
