### ISSUE TITLE
Missing some String format codes

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags-manual#10]
i.e. this is what is documented as available

Code | Description
--- | ---
%d | Integer (use to display value of int and short variables)
%0Xd | Integer left-padded with up to X zeros
%s | String (use to display string variables)
%c | Character (displays the ASCII character of the supplied value)
%f | Float (displays a float variable)
%.Xf | Float to X decimal places
%% | Display the percent character (ie. no variable)
[ | Inserts a new line into the message

...but this works:

    String text = String.Format("%X", 26);
    // text is now "1A"

**Comment by ivan-mogilko** [comment]
AGS uses sprintf internally, therefore it supports everything that C sprintf supports.

**Comment by morganwillcock** [comment]
Wording changed in wiki commit bad90a5b345f9bb503f3881a05984c35e402b1f8
