### ISSUE TITLE
Explain ways of repacking existing game

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags-manual#100]
There's a way someone can repack existing game on disk in order to apply a patch for instance.
If the download size is too big one could try devising a patching procedure using agsutils: https://github.com/rofl0r/agsutils/

There is a serious limitation to this: atm you cannot patch sprites because there's no utility for that, and sprites are packed in their own binary blob.

**Comment by morganwillcock** [comment]
I'm not sure this is within the scope of the project, from a technical or moralistic perspective.

**Comment by ivan-mogilko** [comment]
Well, in the past number of developers complained that they cannot partially patch their game, and that was among the reasons they left using AGS. That was at the time when these utilities already existed.

**Comment by morganwillcock** [comment]
I worry that:

a) documenting it (especially in detail that describes how to do it) implies that this is the supported solution to upgrade your game between versions

b) by promoting the tool directly you inadvertantly make it more acceptable to take a game made by someone else, change the internals, and then make it available for redistribution. I'm not suggesting the games should be encrypted or anything, if people want to open something up they tend to find a way to do it, but I think it is probably not advisable to link to the method to do so in the 'official' documentation
