### ISSUE TITLE
Clarify File.Open using WriteRawLine instead of WriteString

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#104]
If you read the file documentation from top to bottom it starts with `File.Open` :

https://adventuregamestudio.github.io/ags-manual/File.html#fileopen

The example unfortunately uses `WriteString` instead of `WriteRawLine`, so I had a long night trying to understand why my text file had an invalid encoding when loading it. I think it would make sense to use WriteRawLine in the example because one can load a text editor and quickly figure out that the text was written correctly.

**Comment by ivan-mogilko** [comment]
Perhaps there should be another IMPORTANT note there, explaining that there are 2 groups of read/write functions, one is for plain data, and another for "safe" mode where ags detects mistakes if reading is in wrong order.

**Comment by ericoporto** [comment]
I totally had not realized that was the objective of these functions. Yes, that makes sense.
