### ISSUE TITLE
Audio system - need better explanation

### ISSUE THREAD

**Issue by ivan-mogilko2** [adventuregamestudio/ags-manual#107]
Users having trouble with it all the time (AudioChannels, etc).

Once I wrote a post, trying to explain things in nutshell:
https://www.adventuregamestudio.co.uk/forums/index.php?topic=54062.msg636546051#msg636546051

I am not insisting on exact wording, but something similar should be in the manual.

There were few other posts around by me and Snarky (@messengerbag) that mentioned additional nuances.

**Comment by ivan-mogilko** [comment]
Added https://github.com/adventuregamestudio/ags-manual/wiki/AudioInScript, may be enough for starters.
