### ISSUE TITLE
Predefined global script functions are not in index

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#108]
Functions like on_event, on_key_press and so on are no longer in the index, compared to old manual.

Their description can be found on this page: https://github.com/adventuregamestudio/ags-manual/wiki/TextScriptEvents

**Comment by morganwillcock** [comment]
I've [rewritten the page](https://github.com/adventuregamestudio/ags-manual/wiki/Globalfunctions_Event/_compare/6b844a3%5E...6b844a3) and the changes should have fixed this.
