### ISSUE TITLE
on_call callback does not have its own entry

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#109]
Maybe due the fact that's it's a room callback, or simply forgotten, but on_call is not mentioned anywhere except for CallRoomScript entry. Perhaps it may be added to "Predefined global script functions" with a note that it should be placed in a room rather than a regular script module.

**Comment by ericoporto** [comment]
I added a brief entry for it on [here](https://github.com/adventuregamestudio/ags-manual/wiki/Globalfunctions_Event#on_call) and mentioned it on [here](https://github.com/adventuregamestudio/ags-manual/wiki/Globalfunctions_General#callroomscript).
