### ISSUE TITLE
Big table of outdated commands

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#112]
Manual needs an article with big table of outdated/new commands for easier reference.

**Comment by vidzk** [comment]
Hi,
I can work on this project. Can I get more details. I am a content writer and technical writer. I have worked as a business analyst and test analyst. I am looking to gain experience in technical writing.

**Comment by ivan-mogilko** [comment]
> Hi,
> I can work on this project. Can I get more details. I am a content writer and technical writer. I have worked as a business analyst and test analyst. I am looking to gain experience in technical writing.

Hello. I do not think this particular task needs this kind of skill. The point is that there are deprecated script functions, and we need a reference table where old functions are in column 1 and newer replacements in column 2. But this task also requires a good knowledge of AGS scripting language of both old and newer versions.

**Comment by vidzk** [comment]
No, I do not have expertise in AGS. I thought it was a documentation project.

**Comment by ivan-mogilko** [comment]
This repository is for user manual, which in turn is a sub of a larger project of "Adventure Game Studio".

**Comment by morganwillcock** [comment]
@ivan-mogilko For this particular task would someone find all of the previous commands in the existing manual pages or would they have to go back through the source code? I wasn't sure whether the table is only meant to be relevant to the current AGS version and any previous version would be considered outdated, or whether the table is meant to span multiple versions.

**Comment by ivan-mogilko** [comment]
The purpose of this is to let users who upgraded to the latest version find out how to replace deprecated commands. But because they may have used very old functions all this time, it's best to have them all from all the versions below, as much as we can find info about.

The commands may be found in manuals, I believe that 3.4.* manual's index had most of them, with exception of few ancient undocumented functions, notes on which may still be found in pre-3.* manuals. The [script header](https://github.com/adventuregamestudio/ags/blob/master/Editor/AGS.Editor/Resources/agsdefns.sh) may also come useful as it contains everything that engine currently supports, and indicates which functions were obsoleted (using #ifdefs).
It's best to leave engine source code as a last resort.

The table may also contain a column for telling a version which deprecated particular command, or on contrary last version where it was active; but such data would be of less priority.

**Comment by ericoporto** [comment]
I noted the table here in my wiki fork: https://github.com/ericoporto/ags-manual/wiki/Deprecrated-Script-API
Here is the same data in a spreadsheet : [obsolete_ags.ods.zip](https://github.com/adventuregamestudio/ags-manual/files/5330041/obsolete_ags.ods.zip)

This was done manually. I don't know yet how to present this information, should I group it in some way or just leave this big table? I couldn't find the information of the specific version the deprecation happens.

**Comment by ivan-mogilko** [comment]
@ericoporto yes it looks good for starters.
the simplier the better, as this is for user to quickly search for a function.
I think it may need at least 2 columns, as in [your page](https://github.com/ericoporto/ags-manual/wiki/Deprecrated-Script-API): **old api** vs **new api**, with links to new api articles.
That may be extended with a "version" column which tells when the function became outdated.

**Comment by ericoporto** [comment]
OK, I will work on that. I think I can give the version column a try and leave blank the ones I don't know, and they can be filled later.

**Comment by ericoporto** [comment]
I placed the table here: https://github.com/adventuregamestudio/ags-manual/wiki/ObsoleteScriptAPI

I added an entry in the main page itself, but it can be moved elsewhere too. I don't understand why the title look like that...

**Comment by ivan-mogilko** [comment]
I think this may be considered done, any corrections may be dealt with later.
