### ISSUE TITLE
note on enums

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#113]
https://adventuregamestudio.github.io/ags-manual/ScriptKeywords.html#enum

In the page on enums it doesn't explain exactly which values are automatically assigned to them. I think by default it assigns values in sequence starting from 1.

```AGS Script
enum
{
  eA,
  eB,
  eC
}
``` 

Will result in `eA`=1, `eB` =2, `eC`=3. Where if we do:

```AGS Script
enum
{
  eA=0,
  eB,
  eC
}
``` 

We get `eA`=0, `eB`=1 and `eC`=2. The starting number is relevant if one wants to use enums as ~IDs of an array of items. I thought maybe this behavior could be there too.

**Comment by ivan-mogilko** [comment]
Yes, unexpectedly it starts with 1 by default.

Notably it's also possible to assign negative numbers.

**Comment by ericoporto** [comment]
The text I have in mind to add in the enums, just need to make it a little less complicated (maybe by adding example?)

> Each enumerated item of the enum will be assigned a sequential (by increments of 1) integer value, and the first element will be assigned the value of 1. When defining the enum you can set values to specific elements and the ones not set will be assigned sequential values from the assigned elements, in order.

**Comment by ivan-mogilko** [comment]
*In enum each item is assigned an integer value in an order. By default first value is equal to 1, next 2 and so on.*

**Comment by ericoporto** [comment]
Oh, I really like it! It's short and direct!

**Comment by ericoporto** [comment]
Added a description on the [enums](https://github.com/adventuregamestudio/ags-manual/wiki/ScriptKeywords#enum) page to clarify this.
