### ISSUE TITLE
Document Mask Drawing Functions

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#116]
In the upcoming 3.5.1, there are new functions to enable Mask Drawing, they should be documented.

I also find it weird we don't have static objects for `WalkableArea` and `Walkbehind`. After revising all the deprecated commands it seems kinda weird those weren't replaced yet by OOP counterparts.

```AGS Script
/// Gets the drawing surface for the 8-bit walkable mask
import DrawingSurface* GetDrawingSurfaceForWalkableArea();

/// Gets the drawing surface for the 8-bit walk-behind mask
import DrawingSurface* GetDrawingSurfaceForWalkbehind();

/// Gets the drawing surface for the 8-bit hotspots mask
import static DrawingSurface* Hotspot.GetDrawingSurface();     

/// Gets the drawing surface for the 8-bit regions mask
import static DrawingSurface* Region.GetDrawingSurface(); 
```

**Comment by ivan-mogilko** [comment]
> I also find it weird we don't have static objects for WalkableArea and Walkbehind.

True, but I did not feel like adding more new types in 3.5.1.

**Comment by ivan-mogilko** [comment]
The important note should be that masks are not saved on room exit nor in saves, so you have to save some custom data in variables and redraw upon re-entering room.

**Comment by ivan-mogilko** [comment]
Note: all recent API changes are now meant for ags4 branch.

**Comment by ivan-mogilko** [comment]
Done.
