### ISSUE TITLE
Document Skip blocking

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#118]
AGS 3.6.0 brings in `SkipWait()` which can cancel a wait function of any type (`Wait`,`WaitKey`,`WaitMouseKey` and `WaitMouse`). These also need to be documented.

**Moved all Wait related functions** that are global to it's own page:

https://github.com/adventuregamestudio/ags-manual/wiki/Globalfunctions_Wait

---

- [x] Currently Wait functions are here: https://github.com/adventuregamestudio/ags-manual/wiki/Globalfunctions_General

```AGS Script
/// Blocks the script for the specified number of game loops, unless the mouse is clicked.
import int  WaitMouse(int waitLoops = -1);
/// Cancels current Wait function, regardless of its type, if one was active at the moment.
import void SkipWait();
```

- [x] Need an additional SkipSpeechStyle too:

https://github.com/adventuregamestudio/ags-manual/wiki/StandardEnums

```AGS Script
enum SkipSpeechStyle {
#ifdef SCRIPT_API_v360
  eSkipNone         = -1,
```

- [x] Add missing int as return type

```AGS Script
/// Blocks the script for the specified number of game loops.
import void Wait(int waitLoops);
/// Blocks the script for the specified number of game loops, unless a key is pressed.
import int  WaitKey(int waitLoops = -1);
/// Blocks the script for the specified number of game loops, unless a key is pressed or the mouse is clicked.
import int  WaitMouseKey(int waitLoops = -1);
```

Entries also need a see also to: `Game.BlockingWaitSkipped` ( https://github.com/adventuregamestudio/ags-manual/issues/153 )

**Comment by ivan-mogilko** [comment]
Also now Wait functions return the code of how they were skipped.

**Comment by ivan-mogilko** [comment]
Note: all recent API changes are now meant for ags4 branch.

**Comment by ericoporto** [comment]
I am really tempted to move the wait functions from the global general to it's own global "wait" (need to figure a better name). I think it would give proper space for examples on how to use them

**Comment by ivan-mogilko** [comment]
> I am really tempted to move the wait functions from the global general to it's own global "wait" 

Sure.

**Comment by ericoporto** [comment]
Hey, if one does a `SkipWait`, what's the returned reason value?

**Comment by ivan-mogilko** [comment]
> if one does a SkipWait, what's the returned reason value?

0, this is same for timer and script.

**Comment by ericoporto** [comment]
Thanks. I added a mention of it. While there's room for improvement, for the goal of having this information on the manual I consider it done.
