### ISSUE TITLE
Restore TOC links in CHM pages

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags-manual#119]
The TOC links (what shows in the left hand 'frame' of the web site build) should be shown at the top of each CHM page so that if you are at the top you can jump to lower positions in the page using anchor links. The data is already within Pandoc as it is stored as a 'ready to render' TOC for the page, but unfortunately there is no option to shift the headings levels within the TOC, so it is always forced to begin at the first level, and the first level is the page title, so there is heading duplication and a lack of flexibility.

There are likely three ways to add the TOC with a custom starting position:
1. Use the existing global header shift option with a negative shift + a custom filter that implements a positive shift + template changes + heading level changes on the markdown files
2. Look to patch Pandoc to implement a TOC shift in the same way that it already has an option for the global header shift
3. Ignore the built in TOC feature and write a replacement TOC generator based on the page metadata that is already stored using a custom filter or writer

Option 1 isn't too hard to do (I already did it as a test) but it makes a mess of the template structure.

Option 2 would depend on someone writing a patch and it being accepted into Pandoc (I am speaking to someone about how feasible it is as a contracted job, or possibly I will try myself, or possibly a Haskell expert will stumble across this text and decide it is worthwhile).

Option 3 should be feasible, but is really just a poor man's option 2. It is likely preferable to option 1.

**Comment by ericoporto** [comment]
> # Character 
> - Character
>  . Character.Scaling
>  . Character.Clickable
> ---
> ## Character.Scaling
> Ipsum lorem.
>
> ## Character.Clickable
> Lorem ipsum.


The TOC you mention is the one that was in the old LaTeX generated chm like above, right? I do miss those when using the `.chm` version of the manual so I added it in the 3.5.1 milestone.

**Comment by morganwillcock** [comment]
> The TOC you mention is the one that was in the old LaTeX generated chm like above, right?

Yes, that is correct. Your example would be exactly as it would look with no customisation, except that pages potentially have more than one heading, which logically means the TOC needs to be above the first heading and not under it (and this is where it starts to look weird). That said, it probably wouldn't be unreasonable or too difficult to enforce one main heading per page.

**Comment by morganwillcock** [comment]
I've attempted this with a filter. The result looks OK to me and I've quickly checked every page, the only two which looked odd were:

* Pointers.md (would need the existing links at the top of the page to be removed again)
* Tumbleweed.md (might need its own page links list moved futher down page or moved to a separate page as it looks a little stange, although nothing is duplicated so it isn't incorrect)
