### ISSUE TITLE
Disabling inline maths (content fix and removal of build warnings)

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags-manual#12]
I've fixed all of the warnings, except the warnings generated by the lack of maths extension.

This stops all of those warnings:
<pre>import docutils

class math(docutils.nodes.Element):
    pass

def visit_math_html(self, node):
    raise docutils.nodes.SkipNode

def setup(app):
    app.add_node(math, html=(visit_math_html, None))</pre>

...but introduces a new one:
> WARNING: while setting up extension ['conf.py']: node class 'math' is already registered, its visitors will be overridden

...so the maths processing needs to be turned off somewhere within docutils, sphinx, or m2r (I'm not sure which, or whether such a function already exists).

**Comment by morganwillcock** [comment]
Have submitted an option for m2r.
[https://github.com/miyakogi/m2r/pull/28](https://github.com/miyakogi/m2r/pull/28)

**Comment by ericoporto** [comment]
We can use github repos in python through pip with either

    pip install git+https://github.com/morganwillcock/m2r.git

Or directly a line in requirements.txt

    -e git://github.com/morganwillcock/m2r.git#egg=m2r

In case the modification can't be accepted.
