### ISSUE TITLE
Update copyright

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#124]
I think [copyright in the manual](https://github.com/adventuregamestudio/ags-manual/wiki/Copyright) is a bit out of date, at least I don't see anything in regards to new assemblies that Editor uses.
They are mentioned in Credits though. I have no idea why Copyright duplicates some of that info and not the rest...
It does not mention Allegro 4 for some reason either (I think it's giftware fwiw).

And what is this line for? is it necessary?
> Pentium is a trademark of Intel corporation. Windows is a trademark or registered trademark of Microsoft corp.

**Comment by ericoporto** [comment]
There is a list of copyrights that has been reasonably recently updated for the debian package: https://github.com/adventuregamestudio/ags/blob/master/debian/copyright

**Comment by ivan-mogilko** [comment]
Okay, I updated https://github.com/adventuregamestudio/ags-manual/wiki/Credits page, idk what to do with Copyright page, so will leave it for others to bring suggestions if they have any.
