### ISSUE TITLE
Better table presentation in html form?

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#125]
I did not notice this at first, but I am concerned about how table is rendered on page like this:
https://adventuregamestudio.github.io/ags-manual/ObsoleteScriptAPI.html

It does not have any column dividing lines, which makes some column contents visually merge. For example see "Character.IgnoreWalkbehinds" row.

May vertical lines be added, or perhaps some padding, to separate columns in case of very long text?

**Comment by morganwillcock** [comment]
I tried vertical lines but it made short table entries very hard to read because of the high contrast.
I've added some padding instead. https://github.com/adventuregamestudio/ags-manual/commit/1fc8baf96d8cc82c6d093d6afda8965f7a40e68c

**Comment by ivan-mogilko** [comment]
Ah, I see. Yes, padding makes it better.
