### ISSUE TITLE
Update "Runtime engine" article

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#132]
- [wiki/RuntimeEngine](https://github.com/adventuregamestudio/ags-manual/wiki/RuntimeEngine)
- [wiki/EngineConfigFile](https://github.com/adventuregamestudio/ags-manual/wiki/EngineConfigFile)

* [x] Maybe split in multiple articles per topic (config, command line, etc)
* [x] Update command line args to 3.5.1
* [x] Update command line args to 3.6.0
* [x] Update config docs to 3.6.0
* [x] Specifically underline that you must use "--console-attach" on Windows to get stdout in console
* [x] Explain clearly that it's possible to run any game data using engine exe (and on which systems).

**Comment by ericoporto** [comment]
Added acsetup.cfg options and command line args of 3.6.0 on this diff: https://github.com/adventuregamestudio/ags-manual/wiki/RuntimeEngine/_compare/6d31e21%5E...6d31e21

**Comment by ericoporto** [comment]
Added minor notes on using `--console-attach` on Windows and running ags game data on the engine:
https://github.com/adventuregamestudio/ags-manual/wiki/RuntimeEngine/_compare/9bc7551%5E...9bc7551

**Comment by ericoporto** [comment]
> Maybe split in multiple articles per topic (config, command line, etc)

@ivan-mogilko , you mean in different, separate pages?

**Comment by ericoporto** [comment]
Splitted config file to it's own page: https://github.com/adventuregamestudio/ags-manual/wiki/Home/_compare/d0f84ed%5E...d0f84ed

**Comment by ericoporto** [comment]
Added a note to also mention the Android and web port, [in this commit](https://github.com/adventuregamestudio/ags-manual/wiki/_compare/c61b9f5e68a49da920e1a382ceb968c21f83c3c1...7f7c3662064e18af6ec371ea2e51981c6964c396).
