### ISSUE TITLE
Add topics for editor and engine plugin API

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#134]
Here are ones posted on AGS home page:
https://www.adventuregamestudio.co.uk/site/ags/plugins/editor/
https://www.adventuregamestudio.co.uk/site/ags/plugins/engine/

I could not find these topics in the old manual, so probably they were created separately and never got to the repository.

When importing to the manual it's important to scan for any outdated or incorrect information.

**Comment by ivan-mogilko** [comment]
Copied Editor plugin topic: https://github.com/adventuregamestudio/ags-manual/wiki/AGS-Editor-Plugins

Then I realized that don't know how to add images to the topic here...

The engine plugin topic is very long and has special formatting uncommon to markdown, so I decided to leave that for later.

**Comment by ericoporto** [comment]
I started the Engine plugin to markdown api conversion here: https://gist.github.com/ericoporto/80ada012a2bbab8d3cbdc4d6f37188bf

Once I am done with the conversion, I will add some adjustments since some small things need to be adjusted on the text (cross platform stuff)

**Comment by ericoporto** [comment]
I am thinking on moving the plugin samples to GitHub, in a repository they could be maintained. Either each in a repository of their own or one for both.

https://www.adventuregamestudio.co.uk/AGS.Plugin.Sample.zip and https://www.adventuregamestudio.co.uk/agsplugin121.zip

**Comment by ericoporto** [comment]
Moved plugin to `Home.md` and added links to documents on creating plugins there

https://github.com/adventuregamestudio/ags-manual/wiki/Plugins

Added the engine plugin info with some bits adjusted. There's still things to fix, but thought it was best to bring into the wiki to work together.

**Comment by ericoporto** [comment]
I added the missing images. I think it's all done.

**Comment by ivan-mogilko** [comment]
Thank you!

Now added info about the GetRenderStageDesc function (added in 3.5.1).
