### ISSUE TITLE
help should work pressing f1 in ags

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#14]
quoting @ivan-mogilko on [forum](http://www.adventuregamestudio.co.uk/forums/index.php?topic=51340.msg636594148#new):

> Editor sends command to the help file using [Help.ShowHelp from .NET](https://msdn.microsoft.com/en-us/library/f7y1a1xy(v=vs.110).aspx).
> For context-sensitive help the "command" is KeywordIndex and parameter is for example script function name.
> According to the page, compiled help must have "keyword index" inside.

I think the `AGSHelpdoc.hhk` under `build/htmlhelp` contains the original index to be used by the project - according to [docs](https://docs.microsoft.com/pt-br/previous-versions/windows/desktop/htmlhelp/to-assign-a-window-type-to-a-contents-or-index-entry).

Meanwhile I unziped and compared both helps and noticed the current ags-help.chm (from ags itself) has two additional folders inside when compared with the ags-help.chm generated from this repo

![image](https://user-images.githubusercontent.com/2244442/44890159-87a82c80-acaf-11e8-959f-72b8be5e1a99.png)

Also maybe it's not possible to generate it using `chmcmd`, and if this is true we may need to use [HTML Help Workshop](https://docs.microsoft.com/pt-br/previous-versions/windows/desktop/htmlhelp/to-compile-a-help-project-from-the-dos-prompt) - I couldn't find a working current link for it from Microsoft Website. In case this is proven necessary, I found out that it's available through [chocolatey](https://chocolatey.org/packages/html-help-workshop) which can be accessed through [AppVeyor](https://www.appveyor.com/docs/build-configuration/#chocolatey) . Or do the [nextcloud thing](https://github.com/adventuregamestudio/ags-manual/issues/5#issuecomment-408733868)

For now I opened an [issue on chmcmd](https://bugs.freepascal.org/view.php?id=34206) because I think the error is there.

I also found an [unofficial explanation on the chm file format](http://www.nongnu.org/chmspec/latest/index.html) which may be useful or a timewaste, but I am not sure yet.

**Comment by ivan-mogilko** [comment]
> For now I opened an issue on chmcmd because I think the error is there.

But you described the problem wrongly, you are saying that "chmcmd doesn't generate an index", but it does generate an index, you can see it if you open it with help viewer.
It does not generate something else, maybe called "keyword links".

**Comment by ericoporto** [comment]
Thanks Ivan! I wrote a slightly better note on the topic on FreePascal bugtracker to not leave the developer there hanging, but will have to look with care once I am back home.

**Comment by ericoporto** [comment]
![image](https://user-images.githubusercontent.com/2244442/44938705-cc3ad300-ad56-11e8-92bd-e7c399a922ef.png)
_at left the current ags-help.chm BTree, at the right our now generated BTree (please open the image on a new tab)_

So now to the docs... [on WW_Links](http://www.nongnu.org/chmspec/latest/Internal.html#WW_Links) entry, we have on Table 5.38 that the links comes from .hhk file!

Below is a excerpt from our AGSHelp.hhk file generated from sphinx under build/htmlhelp
```
    ...
    </UL><LI> <OBJECT type="text/sitemap">
        <param name="Keyword" value="Functions that return a value">
        <param name="See Also" value="Functions that return a value">
    </OBJECT>
    <UL> <LI> <OBJECT type="text/sitemap">
        <param name="Keyword" value="Scripting Tutorial">
        <param name="Local" value="ScriptingTutorialPart1.html#index-7">
    </OBJECT>
    </UL><LI> <OBJECT type="text/sitemap">
        <param name="Keyword" value="Game / Global functions">
        <param name="Local" value="Game.html#index-0">
    </OBJECT>
    <UL> <LI> <OBJECT type="text/sitemap">
        <param name="Keyword" value="AbortGame">
        <param name="Local" value="Game.html#index-1"> ...
```

So our .hhk file looks like it's correctly populated. But... Using chmcmd throws some errors on the console

```
    ...
    Error: Anchor Game.html#index-0 undefined; first use genindex.html
    Error: Anchor Game.html#index-1 undefined; first use genindex.html ...
```

My guess is that the anchors are broken... So how is this on the `Game.html` generated on `build/htmlhelp` for example?

```
    ...
    <div class="section" id="abortgame">
    <span id="index-1"></span><h2>AbortGame</h2>
    <div class="highlight-guess notranslate"><div class="highlight"><pre><span></span>AbortGame(string message, ...)
    </pre></div>
    </div>
    <p>Aborts the game and returns to the operating system.</p>
    <p>The standard AGS error dialog is displayed, with the script line numbers
    and call stack, along with <em>message</em> ...
```

[So how anchors work? let's see MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a)
> href
> Contains a URL or a URL fragment that the hyperlink points to.
> A URL fragment is a name preceded by a hash mark (#), which specifies an internal target location (an ID of an HTML element) within the current document. 


So we have both abortgame and index-1 as ids near AbortGame, and Game.html#index-1 is the local for the Keyword AbortGame . So... Things look fine? But I don't understand why we have so many errors on the console...

**Comment by ericoporto** [comment]
Ok, I used HTMLHelpWorkshop and build the .chm file...

[Releases](https://github.com/adventuregamestudio/ags-manual/releases/tag/0.1.8) | [ags-help_HTMLHelpWorkshop.chm](https://github.com/adventuregamestudio/ags-manual/releases/download/0.1.8/ags-help_HTMLHelpWorkshop.chm)

aaaaand.... It generates a non-empty BTree file! So maybe there is still something wrong with the chmcmd I built? Well, carry on...

I tried to use it with ags to see if it works.... Aaand it doesn't. I now think we need a small program to debug and findout why f1 doesn't work with the chm files we are making.

**Comment by morganwillcock** [comment]
For reference, here is an decompiled index entry from the working one:
```xml
<OBJECT type="text/sitemap">
  <param name="Local" value="ags73.htm#GetViewportX">
  <param name="Name" value="GetViewportX">
</OBJECT>
```
and here is the equivalent from the new one:
```xml
<OBJECT type="text/sitemap">
  <param name="Keyword" value="GetViewportX">
  <param name="Local" value="Room.html#index-12">
</OBJECT>
```

So there is definitely a difference before the final file is compiled. There is a keyword test tool in HTML Help Workshop, but it keeps crashing (at least for me) so it isn't really usable.

**Comment by morganwillcock** [comment]
Okay, there are probably a couple of different issues with regards to the anchor errors, but the problem of the correct page not opening when pressing F1 does seem directly related to the compiler.

I compiled the source for the old manual with chmcmd and it has the same issue, the same source through hhc.exe works fine.

**Comment by ericoporto** [comment]
@ivan-mogilko what do you think if we used f1 to direct searches in the online manual and ship the chm without context sensitive search as a fallback for the user?

**Comment by morganwillcock** [comment]
> 1. sphinx has wrong stuff when writing the .hhp project. We are fixing with sed.

I compared the settings to the original manual build, and there are less settings present in the working build (it doesn't say Binary Index=No, but it doesn't say anything about Binary Index at all).

> 2. and 3.

But, now I've got a better idea of where the problems are, I'd still like to give the CHM file another ago next week (at least to confirm which problems are from Sphinx and which are from the compiler). I'm pretty busy at the moment, but will try to fit it in.

I think it probably is doable to ship the html build (so effectively, just the web site but offline) with the editor, and get it working with the F1 button, but it would need as good as the CHM file for people to want to switch over.

**Comment by ericoporto** [comment]
I added an appveyor webhook to build on commit and push artifacts once a tag is created. Since the appveyor machine is windows, it uses HTML Help Workshop. To make things easier I used a cygwin environment. Now we still need to solve the sphinx part.

**Comment by morganwillcock** [comment]
Thanks, that is very handy! I'm going to try and solve two problems at once, and move the indexing into a sphinx extension. I think the 'press F1' functionality only works for top level items in the index, plus to work in the same as the old one it needs duplicate entries that include the class names. Hopefully using sphinx config variables, we can set an identifier for the pages containing the Script API and just implement this for those pages, then leave the other content with a single or pair index (what we've got now).

**Comment by morganwillcock** [comment]
Made a slight change to stop disabling the binary index, but here is a build that seems to be working for me when I press F1:

https://ci.appveyor.com/api/buildjobs/nb0y6esv1xungs7d/artifacts/ags-help-HHW.chm
...perhaps give this to the people to test?

The equivalent build with chmcmd still doesn't work, so stick with HHW I guess.

**Comment by morganwillcock** [comment]
@ericoporto it seems that specifying the file encoding within the Sphinx extension breaks the build on Appveyor, but it is still working for me on a local machine. I think the issue is probably related to using the cygwin environment as the shell, but when I made a branch to test the changes it only ran the Travis-CI build.

Is there anything I can change to make the branch also build on Appveyor?

**Comment by ericoporto** [comment]
![pressing_f1_in_ags](https://user-images.githubusercontent.com/2244442/45459484-de116400-b6ce-11e8-8c7f-f7e3d057bccf.gif)

Above is the result of current appveyor.yml build ! So the exactly sames status [as before](https://github.com/adventuregamestudio/ags-manual/issues/14#issuecomment-417823554). I think it's because we have topics inside topics - in the old help, instead we have flat topics. But I think maybe this can be solved on ags itself. 

I looked on the logs and the error on when you used encode in utf-8 [was the encoding](https://ci.appveyor.com/project/ags-manual-ci/ags-manual-4hkmp/build/cygwin-14#L132) keyword in the open function which was solved by using io.open .

**Comment by ericoporto** [comment]
Since #20 we can close this. If there is any problems, we can reopen.

**Comment by marcovtje** [comment]
hello, I'm the author of chmcmd. I'm current redoing the binary index code. What I noticed is also that the current chmcmd ignores the index if it doesn't contain <body>  </body> tags around it.

**Comment by ericoporto** [comment]
@marcovtje can you be more specific? Which input filename for the chmcmd and tags where? Can you point what needs to be different?

**Comment by marcovtje** [comment]
The *.hhk file should have <body> tags. It doesn't interpret the index if no body tags are found

**Comment by morganwillcock** [comment]
@marcovtje just to mention, I accidentally found what seems to break the index. If I just used `chmcmd` with no flags it produced a lot of failed link checks for the anchor links, which look like this:
```
Error: Anchor Viewport.html#viewportx undefined; first use Viewport.html
Error: Anchor Viewport.html#viewporty undefined; first use Viewport.html
Error: Anchor Viewport.html#viewportzorder undefined; first use Screen.html
```
I hadn't considered before that failing the check would remove the item from the index, but I happened to try with `chmcmd --no-html-scan` instead and this leads to everything (including everything in the index) working as expected.

**Comment by ericoporto** [comment]
@morganwillcock  should I reopen this issue? This is related with #102

**Comment by morganwillcock** [comment]
As far as I know the two issues are not related.
