### ISSUE TITLE
dynamic array manual doesn't mention how to resize it

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags-manual#149]
it only mentions how to declare and initialize it with a (at that time) known size.
no mention of how to resize, nor of how to dispose of it.

**Comment by ivan-mogilko** [comment]
There's no way to resize a dynamic array as of now, you have to create a new one and copy contents over.

Disposing of array is the same as for every other managed object created by user: remove all the references (e.g. assign to null).

**Comment by rofl0r** [comment]
> There's no way to resize a dynamic array as of now, you have to create a new one and copy contents over.

that's quite suprising, as it seems to be one of the most basic functionalities expected from a dynamic array.

> Disposing of dynamic array is the same as for every other managed object created by user: remove all the references (e.g. assign to null).

ah, thanks for info.

**Comment by ivan-mogilko** [comment]
Well, it seems to be a "dynamic array" more in a sense of "dynamic allocation". It may be compared with a C-array allocated with malloc (or C++/C# array allocated with new).

**Comment by ivan-mogilko** [comment]
Yes, it's quite primitive, esp. given it did not even have a way to retrieve its length [until recently](https://github.com/adventuregamestudio/ags/pull/1256).

Perhaps more features could be added to it with the new compiler.

**Comment by rofl0r** [comment]
> Perhaps more features could be added to it with the new compiler.

why does that need to be tied to the compiler? couldn't it be implement as a simple call to realloc(), or worst case a convenience function provided that does the "allocate new object, copy old items, dispose old object, return new object" dance ?

**Comment by ivan-mogilko** [comment]
Theoretically that could implemented this way or another. But it all goes down to how to declare this method in script.

Currently ags script does not support generic functions, neither casting to "base object" nor "void*" type.

**Comment by rofl0r** [comment]
thanks for clarification. i'm adding this link to the pr adding .length, for reference https://github.com/adventuregamestudio/ags/pull/1256

**Comment by rofl0r** [comment]
hurr, how can one actually create a dynamic arrray of a struct ?
i'm trying this

```c
managed struct gditem {
        int hash;
        char s[64];
};      
gditem gditems[];
```
but compiler complains: `Error (line 210): Cannot declare local instance of managed type`

**Comment by ericoporto** [comment]
it has to be 
```AGS Script
gditem* gditems[];
```

**Comment by ivan-mogilko** [comment]
"managed" structs cannot be instanced directly, you have to have a pointer to them.

For unknown reasons the old compiler cannot create dynamic array of regular structs.

**Comment by rofl0r** [comment]
> it has to be
> gditem* gditems[];

thanks, that seems to work in that it compiles.

however when i create the array, i can't actually access the storage, e.g.

```c
managed struct gditem {
	int hash;
	char s[64];
};
gditem* gditems[];

int gdcount = 0;
int gddim = 0;

void add_gd_entry(String value) {
	string temp;
	StrCopy(temp, value);
	if(gdcount +1 > gddim) {
		gditem* gditems_new[];
		int gddim_old = gddim;
		if(gddim == 0) gddim = 32;
		else gddim = gddim * 2;
		gditems_new = new gditem[gddim];
		int i;
		for(i = 0; i < gddim_old; i++)
			gditems_new[i] = gditems[i];
		gditems = null;
		gditems = gditems_new;
	}
	int h = shash(temp);
	gditems[gdcount].hash = h;
	StrCopy(gditems[gdcount].s, temp);
	gdcount++;
}

```

when i try to access `gditems[gdcount].hash = h;` i get `Error: Null pointer referenced`

if i declare the dynamic array like that, is each array member of struct type, or just a pointer to my struct ? i also tried `gditems[gdcount] = new gditem` but that fails with `Operator cannot be applied to this type`.

**Comment by ericoporto** [comment]
```
int count = size_rofl0r_array;
gditems = new gditem[count];
for(int i=0; i<count; i++) gditem[i] = new gditem;
```

**Comment by rofl0r** [comment]
> for(int i=0; i<count; i++) gditem[i] = new gditem;

that doesn't work, see my prev statement:

> i also tried gditems[gdcount] = new gditem but that fails with Operator cannot be applied to this type.

i'm trying to reimplement the bits of the spaghetti code collection known as "agswave" that are used in StrangeLand in pure ags script in order not having to deal with plugin compilation, and the issues caused by mixing SDL2_sound with SDL_sound, etc.

**Comment by ericoporto** [comment]
There are two `new` calls, read my code again.

And you should really read agswave source code, it does things that are not possible in AGS overall, the code is open, just modify it and PR back.

**Comment by rofl0r** [comment]
> There are two new calls, read my code again.

yeah, in mine too:

```c
gditems_new = new gditem[gddim];
gditems = gditems_new;
gditems[gdcount] = new gditem; // -> Operator cannot be applied to this type
```

> And you should really read agswave source code, it does things that are not possible in AGS overall

i'm pretty sure that it should be possible to do most things that are actually used. agswave is 5 KLOC collection of all sorts of unrelated things, basically it's Dualnames' "standard library", and its use of SDL_sound isn't compatible with SDL2_sound used in 3.6.0+. it does font stuff, sound stuff, music stuff, silly things like a replacement of GetGlobalint, just that the ints are converted into strings and back, etc.

**Comment by ericoporto** [comment]
Before assessing the hash you are trying to access, to store, you need to allocate that element.

**Comment by rofl0r** [comment]
> Before assessing the hash you are trying to access, to store, you need to allocate that element.

yeah, and that doesn't work, as i repeat now for the 3rd time, it causes: Operator cannot be applied to this type, at least in old compiler.

**Comment by ericoporto** [comment]
Is this error at runtime or compile time?

**Comment by ericoporto** [comment]
I am closing this because it's not really a problem in the manual. For help with scripting, this is not the channel.

The issue of lacking resize and additional capabilities is a lack of generics support in the script language, this should be a new, separate, issue in AGS repository. 

AGS Script is not C and generics is the way to go.

**Comment by ivan-mogilko** [comment]
@rofl0r I used this code for a test:

<pre>
managed struct gditem {
	int hash;
	char s[64];
};
gditem* gditems[];

int gdcount = 0;
int gddim = 0;

import int shash(string s);

void add_gd_entry(String value) {
	string temp;
	StrCopy(temp, value);
	if(gdcount +1 > gddim) {
		gditem* gditems_new[];
		int gddim_old = gddim;
		if(gddim == 0) gddim = 32;
		else gddim = gddim * 2;
		gditems_new = new gditem[gddim];
		int i;
		for(i = 0; i < gddim_old; i++)
			gditems_new[i] = gditems[i];
		gditems = null;
		gditems = gditems_new;
	}
	int h = shash(temp);
	gditems[gdcount] = new gditem; // <---------------
	gditems[gdcount].hash = h;
	StrCopy(gditems[gdcount].s, temp);
	gdcount++;
}
</pre>

Notice I added `gditems[gdcount] = new gditem;` (I did this for a quick test, not certain if it's right line).

There are no compile errors (used AGS 3.5.1).

**Comment by ivan-mogilko** [comment]
@ericoporto actually, this issue started as:

> it only mentions how to declare and initialize it with a (at that time) known size.
no mention of how to resize, nor of how to dispose of it.

I think it may be worth mentioning this information in the manual too.

**Comment by ericoporto** [comment]
@ivan-mogilko you can't multiply the array size by 2 and then only add 1 element there, either it only declare when adding or do new for every other element. Try to add 34 elements and you will see it fail.

**Comment by ivan-mogilko** [comment]
> you can't multiply the array size by 2 and then only add 1 new element there

What do you mean? Of course I can, the rest will contain nulls.

**Comment by ivan-mogilko** [comment]
Ok, I see now, that was about a wrong place to add a `new gditem` line. I added it following the above comment by rofl0r, because my goal was to test compilation rather than how it works and I did not read through the code. Of course it should be added before `gditems[gdcount].hash = h;` line.

So I fixed it now in the above code.

@rofl0r , by the way, following two lines may be squashed:
```
gditems = null;
gditems = gditems_new;
```
into just `gditems = gditems_new;`, it will have same result

**Comment by ivan-mogilko** [comment]
Added explanation on resize/delete to [the article](https://github.com/adventuregamestudio/ags-manual/wiki/DynamicArrays).

Ended up writing bit more than planned, hope it's elaborate.

**Comment by rofl0r** [comment]
> Added explanation on resize/delete to the article.

thanks, very helpful! i suspect the obscurity regarding dynamic arrays is one of the main reasons why people write fugly plugins like agswave. but then, the author of that plugin didn't seem to ever listen to your advices you gave him in the forum, but continued in his NIH effort.

> @rofl0r , by the way, following two lines may be squashed:
> gditems = null;
> gditems = gditems_new;

oh, good to know, thanks!

>        gditems[gdcount] = new gditem; // <---------------

hurr, turned out that it errored because i did

`if(!gditems[gdcount]) gditems[gdcount] = new gditem;` but apparently ags compiler isn't aware that !something is equal to something == 0 or something == null.

> gditem gditems[];
> but compiler complains: Error (line 210): Cannot declare local instance of managed type

meanwhile i added support for POD, non-managed struct to agscc: https://github.com/rofl0r/ascc/commit/c6c8e373dc7bbbb53dca09eeee26414d35ba5932

i.e. the syntax gditem gditems[]; now works as expected and as it would in C.
