### ISSUE TITLE
Document character Idle Delay property

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#163]
Since AGS 3.6.0, a new property, IdleDelay is available for characters through the Editor setting, but NOT for Scripting.

`IdleDelay` property is the Delay before the idle view activates, in _seconds_.

Not sure where to document it, or maybe not document it at all? It would be an entry update somewhere, just don't know where.

https://github.com/adventuregamestudio/ags-manual/wiki/Character#characteridleanimationdelay

**Comment by ivan-mogilko** [comment]
There's a [Character Editor](https://github.com/adventuregamestudio/ags-manual/wiki/EditorCharacter) page, but it does not describe individual properties, so unless it does there's no point of mentioning this new one anywhere. IMO it's better to open a new ticket about adding property table & descriptions in these "editor" pages.

**Comment by ericoporto** [comment]
> PS. to clarify, in scripting it's set using Character.SetIdleView which has 2 parameters (view, delay).

Ah, that is interesting. 

> IMO it's better to open a new ticket about adding property table & descriptions in these "editor" pages. 

Good idea, I had not thought about that. I will look into how it would be to roll something like that and open it's own ticket for it.

**Comment by ericoporto** [comment]
so, to update this, we eventually added IdleAnimationDelay property:

```AGS Script
  /// Gets/sets the character's idle animation delay.
  import attribute int  IdleAnimationDelay;
```

**Comment by ivan-mogilko** [comment]
I'd like to close this, because, as explained earlier, it does not make sense to add this 1 property's description while no properties are described for Character's editor. It would only make sense to describe all the available properties at the time of writing.
