### ISSUE TITLE
Document arbitrary file packaging ("$DATA$" location token for file paths)

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#164]
Need to add mention to new `"$DATA$"` location token for file paths. Currently these tokens are documented below:

https://github.com/adventuregamestudio/ags-manual/wiki/File#fileopen

The information that is added in General Settings should be added here:

https://github.com/adventuregamestudio/ags-manual/wiki/GeneralSettings#compiler

More details on: https://github.com/adventuregamestudio/ags/pull/1372

> - Resources packaged like this are assigned names containing full relative path. For example: Data/subdir/myfile.dat. The topmost dir name is also kept - to easily avoid filename conflicts with the rest of the game files.
> - To be precise, the path slashes are forced to strictly forward style. This may be important when opening these files in script; although we might adjust engine's behavior to support both ways when opening resources from a package (frankly, I don't remember if it already does that).
> - These files may be opened in script using a new filepath token "`$DATA$`" (as described in AGS 4: Support reading from game assets in script #1294), for example:
> ```
> File* f = File.Open("$DATA$/Data/subdir/myfile.dat", eFileRead);
> ```
> - To clarify once more, just in case, `$DATA$` token only allows to open files for reading.

**Comment by ivan-mogilko** [comment]
> Additionally, the setting itself in General Settings. Currently we DON'T HAVE a page for General Settings, which is unfortunate.

I think since there's a "Editor" section now, General Settings may be just created under the same section by simply copying existing text.

**Comment by ericoporto** [comment]
Yeah, I think this would work! Maybe also either making each category a subtitle or the item themselves a subtitle, just to be able to reference specific settings from other places.

**Comment by ericoporto** [comment]
Added a small entry in General Settings page here:
https://github.com/adventuregamestudio/ags-manual/wiki/GeneralSettings#compiler

This contains the new `Package custom data folder(s)` option.

**Comment by ericoporto** [comment]
added a tiny mention to the `$DATA$` token: https://github.com/adventuregamestudio/ags-manual/wiki/File/_compare/4219d93%5E...4219d93

**Comment by ericoporto** [comment]
Done
