### ISSUE TITLE
Document new Overlay properties and changes

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#165]
Need to update Overlay entry here for the additional properties
https://github.com/adventuregamestudio/ags-manual/wiki/Overlay

```
/// Gets the width of this overlay.
readonly attribute int Overlay.Width;
/// Gets the height of this overlay.
readonly attribute int Overlay.Height;
/// Gets/sets the transparency of this overlay.
attribute int Overlay.Transparency;
/// Gets/sets the overlay's z-order relative to other overlays and on-screen objects.
attribute int Overlay.ZOrder;
```

Overlay.ZOrder lets you to define overlay's drawing order on screen. Overlays are now sorted among GUIs. So it's important to mention them on the See Also part of the entry!
https://github.com/adventuregamestudio/ags-manual/wiki/GUI#guizorder

Additionally, Overlays now are unlimited, so we need to remove the limits mentioned below
https://github.com/adventuregamestudio/ags-manual/wiki/SystemLimits

**Comment by selmiak** [comment]
well, I updated the system limits entry for now :)
Is this the way it works? I mean, 3.6 is not out so the manual is kind of wrong for the time until the release of 3.6...

**Comment by ericoporto** [comment]
Uhm, I think we could have branches for each version maybe, and then just build each branch and then AGS could download only the one corresponding to the branch, but for the time being,  for this particular page, what I can do is search around the changelogs for when each limit changed and turn this into a table with a version like current limit, version since it's said limit, last limit before version change.

**Comment by selmiak** [comment]
or we just add something to the manual like
- unlimited screen overlays at a time (since AGS version 3.6)
or
- unlimited screen overlays at a time (since AGS version 3.6, previous limit: 20)

this is interesting info for software archaelogists and nerds and can make people just update to the newes AGS version :)

**Comment by ivan-mogilko** [comment]
Yes, having table of limits history may also have sense, we already have a table of deprecated functions.

**Comment by ericoporto** [comment]
> IMO it's best to have a table separately, maybe below the current limits list, as it will let to have several entries for a type (one entry per limit change). 

Ah, like a changelog of limits? That could work! I will gather the data and present here or a new issue before adding in. :)

**Comment by selmiak** [comment]
well, I did put together the lifted limits from 3.5 and 3.6.
No idea if I got them all, I got the info from the history of the wiki page. feel free to move things around, reword and add to the list!

**Comment by ericoporto** [comment]
Added the new Overlay properties here: https://github.com/adventuregamestudio/ags-manual/wiki/_compare/85159ec2fe8dcb7e982f2a190e8b44075b836732...a8cbf0ecf7e2063a11e085b20d0e0afccac5ccec

But I am not having an idea for an example for them right now.

**Comment by ericoporto** [comment]
this issue is still visible from https://github.com/adventuregamestudio/ags-manual/issues/155 so I will close it
