### ISSUE TITLE
Document Translation with UTF-8

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#167]
The translations entry needs to be updated to reflect the UTF-8 changes. This includes also new keywords!
https://github.com/adventuregamestudio/ags-manual/wiki/Translations

There's a lot on the topic written here:
https://www.adventuregamestudio.co.uk/forums/index.php?topic=59240.0

And as mentioned [here](https://www.adventuregamestudio.co.uk/forums/index.php?topic=58976.msg636637643#msg636637643):

> AGS now supports Unicode translations, if your TRS files are saved as UTF-8 and certain hint is added to the files, engine should correctly interpret the text as unicode, and display unicode texts with appropriate fonts.
>  
> In short, you should have following line among the other options in TRS file:
> ```
> // Text encoding hint
> //#Encoding=UTF-8
> ```
> The translation compiler will add it to TRA data, to let engine know to interpret these translations as unicode.
> If there's no such line, or value it empty, - it will be interpreted as ASCII.
> 
> And TRS should of course be saved as UTF-8 (plain UTF-8, without BOM!).

Need to check this against the entry above and update and add new information.

**Comment by ericoporto** [comment]
minor addition in the Translation: https://github.com/adventuregamestudio/ags-manual/wiki/Translations/_compare/1baa3e3%5E...1baa3e3

**Comment by ivan-mogilko** [comment]
I think this has a minimal necessary information already.
