### ISSUE TITLE
Add screenshot image to translations article

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags-manual#169]
![addtranslation](https://user-images.githubusercontent.com/22618469/133994551-e2cd2504-fb74-41eb-94e7-cc28c6414306.png)
 this would go nice with this article
https://github.com/adventuregamestudio/ags-manual/wiki/Translations

but I have no idea how to add images to the wiki article. maybe I can embed the image from issue...

**Comment by selmiak** [comment]
well, the image now has a github url and embeds for me. someone more knowledgable please add it in the way it is supposed to be added...

**Comment by ericoporto** [comment]
I will add it directly to the wiki itself, thanks @selmiak !

**Comment by ericoporto** [comment]
done: https://github.com/adventuregamestudio/ags-manual/wiki/_compare/21b348d6ce9fc6c1ceb6986b98791c941731e0e7...82e46266016b37cd312c774a38c8a8f5fa8f0533
