### ISSUE TITLE
Mention possible param values of Set.Create & Dictionary.Create

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#172]
I just noticed that although Dictionary.Create and Set.Create articles mention they accept args of SortStyle and StringCompareStyle, but they don't tell which values may be used there. This is inconvenient, as a person will have to search the manual to find how these enums look like (or refer to editor's autocomplete).

**Comment by ericoporto** [comment]
Add a mention 

Dict: https://github.com/adventuregamestudio/ags-manual/wiki/_compare/594d296027b13562be3046af53e5a54b78b56390...ee3d398e85ff86dc0d1f40ea6d20fdd15eba8002
Set: https://github.com/adventuregamestudio/ags-manual/wiki/_compare/ee3d398e85ff86dc0d1f40ea6d20fdd15eba8002...11e8b1c6641d45549471ff746fb28f9a97780e45

The enums also already point to these 

https://github.com/adventuregamestudio/ags-manual/wiki/StandardEnums#sortstyle

Maybe we could also add StandardEnums link through `see also:` cues.
