### ISSUE TITLE
Document on_key_press and on_text_input

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#174]
- Expanded `on_key_press` callback, now supports two parameters: key code and key modifier flags.
 - In the new key handling mode `on_key_press` is called for each actual key press;
   e.g. combinations like Ctrl+Z will result in two `on_key_press` calls, one with eKeyCtrlLeft and
   second with eKeyZ; added support for "NEW_KEYINPUT_API" macro in scripts.
 - Implemented new `on_text_input(int ch)` callback which is called when the engine receives
   a printable character. This callback is essential for handling unicode chars in script.

https://github.com/adventuregamestudio/ags-manual/wiki/Globalfunctions_Event

---

Explain how utf-8 and ansi mode influence this.

Forum mention of this https://www.adventuregamestudio.co.uk/forums/index.php?topic=58976.msg636644247#msg636644247

**Comment by ericoporto** [comment]
May require some additional notes here too: https://github.com/adventuregamestudio/ags-manual/wiki/ASCIIcodes

**Comment by ivan-mogilko** [comment]
I think this is done now, at least the main information; also added NEW_KEYINPUT_API to https://github.com/adventuregamestudio/ags-manual/wiki/Constants
