### ISSUE TITLE
Document new eKeyMod and new eKey for Shift, Control and Alt keys.

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#176]
Added [eKeyMod](https://github.com/adventuregamestudio/ags/blob/master/Editor/AGS.Editor/Resources/agsdefns.sh#L366)

```
enum eKeyMod
{
  eKeyModShiftLeft,
  eKeyModShiftRight,
  eKeyModShift,        // this means: any shift
  eKeyModCtrlLeft,
  eKeyModCtrlRight,
  eKeyModCtrl,         // this means: any control
  eKeyModAltLeft,
  eKeyModAltRight,
  eKeyModAlt,           // this means: any alt
  eKeyModNum,        // numlock
  eKeyModCaps         // capslock
};
```

and added eKeys:

```
  eKeyShiftLeft,
  eKeyShiftRight,
  eKeyCtrlLeft,
  eKeyCtrlRight,
  eKeyAltLeft,
  eKeyAltRight,
```

Update following pages:

https://github.com/adventuregamestudio/ags-manual/wiki/StandardEnums
https://github.com/adventuregamestudio/ags-manual/wiki/ASCIIcodes

---

Forum mention

https://www.adventuregamestudio.co.uk/forums/index.php?topic=58976.msg636644247#msg636644247

**Comment by ivan-mogilko** [comment]
Done in keycodes page: https://github.com/adventuregamestudio/ags-manual/wiki/Keycodes
