### ISSUE TITLE
Update information on supported sound formats

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#180]
https://github.com/adventuregamestudio/ags-manual/wiki/MusicAndSound

Where it sais about supported formats.

1. Remove a note about OGG being free compared to MP3. Using MP3 no longer requires legal fees.
2. Currently supports WAV of 4, 8, 16, 24 and 32-bit sample format.

I'm not fully certain, but there were some OGG encodings that did not work, like flac (need to double check).

**Comment by ericoporto** [comment]
Removed the non-free information here: https://github.com/adventuregamestudio/ags-manual/wiki/MusicAndSound/_compare/69e519c%5E...69e519c

**Comment by ericoporto** [comment]
From https://github.com/icculus/SDL_sound :

 - Wave (.WAV) files
 - MPEG-1 layers I-III (.MP3, .MP2, .MP1)
 - Ogg Vorbis (.OGG) files
 - Free Lossless Audio Codec (.FLAC) files
 - Audio Interchange format (.AIFF) files
 - Sun/NeXT Audio (.AU) files
 - Shorten (.SHN) files
 - Creative Labs Voice (.VOC) files
 - Various "module" formats (.MOD, .669, .AMF, .XM, .IT, .S3M, .STM, etc)
 - MIDI (.mid) files
 - Raw PCM data

**Comment by ericoporto** [comment]
I think the Editor is "limited" by what's available for the Irlicht media component. So perhaps we use the last list of formats you sent (in AudioComponent.cs) and then in the future create a new ticket and devise a way to use SDL_sound in the editor instead.

**Comment by ivan-mogilko** [comment]
> I think the Editor is "limited" by what's available for the Irlicht media component. 

It's not really limited to that, the media component affects only the preview, but no the game compilation.

**Comment by ericoporto** [comment]
We could use this table in the manual right now, and then add more once we remove limitations in the Editor, but we also will need to verify they actually work in SDL_sound as advertised!

extension| Name
-------|--------
`.ogg` | Ogg Vorbis
`.wav` | Wave (8, 16, 24 and 32 bit)
`.mp3` | MPEG-1 Audio Layer III
`.voc` | Creative Labs Voice
`.mid` | MIDI (requires Soundfont)
`.mod` | ProTracker / NoiseTracker MOD
`.xm`  | FastTracker II
`.s3m` | ScreamTracker file
`.it`  | Impulse Tracker

**Comment by ericoporto** [comment]
I think this is enough on sound formats, a new issue can be created if need
