### ISSUE TITLE
Document Editor Preferences

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#183]
I don't remember if there is an article for Editor Preferences, so we need to either create one or amend with 3.6.0 changes.

Need a description of available options.

**Comment by ericoporto** [comment]
I could not find one, so we should make one. I think I will just follow everything there is in the advanced tab

**Comment by ericoporto** [comment]
Added a initial version by pulling directly from the preferences properties:

https://github.com/adventuregamestudio/ags-manual/wiki/EditorPreferences
