### ISSUE TITLE
Document Spritefile (acsprset.spr) can now be recreated in the editor

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#188]
Need to figure where to add this information in the documentation.

**Comment by ivan-mogilko** [comment]
For good results need to explain how the sprites are stored in the project, what is "source file", how to recreate sources if they are missing (using "export all" with an option to connect source to exported file), etc.

We have a [Sprite Manager](https://github.com/adventuregamestudio/ags-manual/wiki/EditorSprite) topic, perhaps it could be used for this purpose.

**Comment by ericoporto** [comment]
Added a bit of information in the suggested topic: https://github.com/adventuregamestudio/ags-manual/wiki/EditorSprite/_compare/6bff301%5E...6bff301

**Comment by ericoporto** [comment]
Noticed there are thing in Settingupthegame that could be moved to the Sprite Manager topic... https://github.com/adventuregamestudio/ags-manual/wiki/Settingupthegame#importing-your-own-sprite-graphics

**Comment by ivan-mogilko** [comment]
Updated a little more, I think this may be closed now.
