### ISSUE TITLE
Game. functions missing

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags-manual#189]
before I add those missing ones in too, let me first know if sorting these Game. functions by alpha was okay or if there was a reason for the other sorting, so reverting that is easier.
The missing Game. functions are:

Game.SetAudioTypeSpeechVolumeDrop
Game.SetAudioTypeVolume
SetSpeechVolume
Game.StopAudio

**Comment by ericoporto** [comment]
We usually have function (methods) listed first and then properties are listed after. Usually the ordering is more by proximity than alphabetically I think, because the index has the things ordered alphabetically, but it may be how things got written organically. I need time to check if anything disappeared in the ordering, the commit changes were a lot of lines and I had not had the time to check everything.

**Comment by ivan-mogilko** [comment]
All of these functions exist in the manual, you can find them in the index. This means that they are located not on their page.
Here they are:
https://github.com/adventuregamestudio/ags-manual/wiki/Multimedia

**Comment by selmiak** [comment]
> We usually have function (methods) listed first and then attributes (properties) are listed after.

okay, didn't know that, that kind of makes sense, as a user I find things faster when they are sorted by alpha.

The game page has a headline (the h2 type) of **Game functions**, (mentioning only functions) even though it lists functions _and_ properties, for example the GUIs functions and properties page has a h2 headline of **GUI functions and properties**, that is more correct, but it would make even more sense then to have two h2 headlines manual wide,
over the list of function and properties.
in case of the Game. functions and properties that would mean to have a h2 called **Game functions**, then list the functions, then another h2 **Game properties** and list the properties by alpha to create the headlines and links.

for quick reference:
https://github.com/adventuregamestudio/ags-manual/wiki/Game (only has a functions headline)
https://github.com/adventuregamestudio/ags-manual/wiki/GUI (has a functions and properties headline)

**Comment by ericoporto** [comment]
I reverted the commit, but there was some GitHub weirdness in it that didn't got into effect at the time, but it appears reverted now.

**Comment by ivan-mogilko** [comment]
Moved remaining articles from Multimedia to Game page:
https://github.com/adventuregamestudio/ags-manual/wiki/Game/_compare/48a1d7f5f16fce1f850d61cc09d8a1a2084852e7...5b6f64b8b794c1e2e5800cc082127e93f38046c4

**Comment by selmiak** [comment]
in the 3.5 manual SetSpeechVolume is also listed as a Game. function, but with that syntax probably a multimedia function.
if that function is really multimedia and not a game function then this can be closed.
