### ISSUE TITLE
Document the order of game updates and script callbacks in AGS

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#190]
These are so messed up ("historical" reasons!) that I keep forgetting them myself, and give wrong advises to people.

From double-checking the code, the actual order of things in AGS is this:

```rep_exec_always > main game update > late_rep_exec_always > screen shaking > mouse position update > gui visual poll (react to mouse over etc) > render > rep_exec and all other events (scheduled during this frame) > room background animation update```.

Yes that's weird.

**Comment by ericoporto** [comment]
There's some related information here: https://github.com/adventuregamestudio/ags-manual/wiki/BlockingScripts

**Comment by ivan-mogilko** [comment]
Btw, it's probably wrong and relates to some old state of the engine, because it mentions 3 script "threads" while engine currently has only 2.

**Comment by ivan-mogilko** [comment]
BTW that page is kind of wrong, because there are not 3 but 2 "threads". Probably the "room thread" was split out to illustrate the relation between global script and room, it even sais that room events still run on the global thread.

**Comment by ivan-mogilko** [comment]
Added new page: https://github.com/adventuregamestudio/ags-manual/wiki/GameEventsOrder

Linked from here: https://github.com/adventuregamestudio/ags-manual/wiki/ScriptingLanguage

Could be moved elsewhere later if it's bad.
