### ISSUE TITLE
Document Character Animate volume parameter and AnimationVolume 

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#191]
https://github.com/adventuregamestudio/ags-manual/wiki/Character#characteranimate

```
  /// Gets/sets the volume modifier (0-100) of frame-linked sounds for this character.
  import attribute int  AnimationVolume;
```

Need to update to include information on how View sounds and AnimationVolume and the volume parameter in Animate works

> NOTES: On Animation volume
> 
> Previously there was no way to choose the playback volume of sounds linked to the animation frames. The only related property was Character.ScaleVolume.
> Now there are two ways to do this. First of all, there's Character.AnimationVolume. It sets the default relative volume of any frame sounds. For example, here's a primitive example of how you can make the footsteps volume depend on the character's X position in room:
> Code: Adventure Game Studio
> `player.AnimationVolume = player.x * 100 / Room.Width;`
> 
> Secondly, each Animate() function (for Button, Character and Object) now has a "volume" parameter. Passing -1 (default) will ignore this, but when a 0-100 value is passed, that value overrides the frame sound volume.
>

**Comment by ivan-mogilko** [comment]
> Secondly, each Animate() function (for Button, Character and Object) now has a "volume" parameter. Passing -1 (default) will ignore this, but when a 0-100 value is passed, that value overrides the frame sound volume.

So, I first had an idea of Animate() overriding Character.AnimateVolume, but then I rethought that and instead made them relative instead. I made this comment to the commit:

> We view the audio property (volume) relation as the relation of the entities:
system -> audio type -> audio emitter (character) -> animation's audio
therefore the sound volume is a multiplication of factors.

**Comment by ericoporto** [comment]
Ah, that is a good one, probably 100 is a better default, yes. I just noticed Objects also has a -1, but it doesn't have an AnimateVolume, which is fine, I am just curious on the `-1`.

**Comment by ivan-mogilko** [comment]
Done, added info about Character.AnimationVolume, and Animate's volume param for all 3 types (char, button, object).
