### ISSUE TITLE
Document Overlay.CreateRoomGraphical and CreateRoomTextual

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#192]
https://github.com/adventuregamestudio/ags-manual/wiki/Overlay

These two functions to create "room overlays": that is - overlays that display a sprite inside the room, sorted among other room objects, characters and walk-behinds.

```AGS Script
  /// Creates an overlay that displays a sprite inside the room.
  import static Overlay* CreateRoomGraphical(int x, int y, int slot, bool transparent = true, bool clone = false);
  /// Creates an overlay that displays some text inside the room.
  import static Overlay* CreateRoomTextual(int x, int y, int width, FontType, int colour, const string text, ...);
```

Overlays still remain a simplistic kind of object that does not have any automated behavior, so it won't interact with anything inside the room, but it still may be sorted among other objects there by manually setting Overlay.ZOrder. 

If you'd like room overlay to change its "baseline" along with its vertical position, you will have to do something like this in rep-exec:

```AGS Script
over.ZOrder = over.Y + over.Height;
```

Room overlays open new possibilities in making temporary visual effects in the game, and also may help to script custom game elements from ground up (as they have no additional functionality on them).

Additionally, **`Overlay.InRoom`** property is added:

```AGS Script
  /// Gets whether this overlay is located inside the room, as opposed to the screen layer.
  import readonly attribute bool InRoom;
```

**Comment by ivan-mogilko** [comment]
Done.
