### ISSUE TITLE
Document Android and Web setup in the Editor

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#194]
There's "Distributing your game" page that has a minimal information about building for different ports.
https://github.com/adventuregamestudio/ags-manual/wiki/DistGame

Building for Android requires significantly more setup than Windows and Linux, therefore it's essential to have that documented.
I think it's also worth documenting how to run compiled game for the web; at least the basics of it.

NOTE: Android preferences are already mentioned in https://github.com/adventuregamestudio/ags-manual/wiki/EditorPreferences

**Comment by ericoporto** [comment]
Added Android build initial information here: https://github.com/adventuregamestudio/ags-manual/wiki/BuildAndroid
Linked from here: https://github.com/adventuregamestudio/ags-manual/wiki/OtherFeatures

**Comment by ericoporto** [comment]
Linked to Building for Android from DistGame: https://github.com/adventuregamestudio/ags-manual/wiki/DistGame/_compare/4077bd2%5E...4077bd2

**Comment by ericoporto** [comment]
@selmiak since you are playing with the web port, if you have ideas to clarify or what is important to mention, feel free to do so.

I wrote a very minimal text here: https://github.com/adventuregamestudio/ags-manual/wiki/DistGame

**Comment by ericoporto** [comment]
I am going to consider this as done, but we can open issues to improve things anytime.
