### ISSUE TITLE
Write a updating to AGS 3.5.1

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#196]
Thinking about if it makes sense to write a page for this - we skipped this in 3.5.1 at the time of it's release.

So far the only change I have in my head is about config changes not being automatically written anymore, from [Amir's post](https://www.adventuregamestudio.co.uk/forums/index.php?topic=60039.0) on the forums.

- config not automatically saved - requires `System.SaveConfigToFile()`
- mention `$CONFIGFILE$`
- global config in Windows

Erh, besides config it looks like 3.5.1 is mostly a gazillion bug fixes?

**Comment by ivan-mogilko** [comment]
Strictly speaking config is no longer saved since 3.5.0.

**Comment by ericoporto** [comment]
I think I will close this as 3.5.1 time is passed.
