### ISSUE TITLE
Update to FAQ to address the text parser

### ISSUE THREAD

**Issue by stackdragon** [adventuregamestudio/ags-manual#197]
Is there any interest in updating the FAQ to state clearly that the engine supports the creation of games that use a text parser?

Something like:

**Q. Can I create games that use a text parser, similar to the classic Sierra adventure games, such as King’s Quest and Space Quest?**

A. Yes, AGS allows for the development of games that use text parser input. It is possible to create games that use an “always on” text parser (used in AGI games, such as Kings Quest I) as well as a “pop up” text parser (used in SCI games such as Space Quest 3).

**Comment by ericoporto** [comment]
I think that looks fine, please also add a link to the text parser article. Something like

```
Se more in the [Text Parser](TextParser) topic in the manual.
```

**Comment by stackdragon** [comment]
Done. Thanks.

**Comment by stackdragon** [comment]
Noted. And thanks so much for your work with AGS. I am really enjoying using it.
