### ISSUE TITLE
Obsolete licensing information

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#198]
Let's ensure the following is updated (kept the original text below)

- https://github.com/adventuregamestudio/ags-manual/wiki/Credits
- https://github.com/adventuregamestudio/ags-manual/wiki/Copyright
- https://github.com/adventuregamestudio/ags-manual/wiki/DistGame#licensing

---

Randomly noticed this paragraph: https://github.com/adventuregamestudio/ags-manual/wiki/DistGame#licensing

OGG Player (alogg) and MP3 player (almp3) information is refering to old allegro-based players. Same problem is found in https://github.com/adventuregamestudio/ags-manual/wiki/Copyright

I think today we should mention SDL2, SDL_Sound, mojoAL, and perhaps partial use of allegro4 code.

**Comment by ericoporto** [comment]
> I think today we should mention SDL2, SDL_Sound, mojoAL, and perhaps partial use of allegro4 code.

For the copyright page I added partial information here:

https://github.com/adventuregamestudio/ags-manual/wiki/Copyright/_compare/72b46d2%5E...72b46d2

I think we also need to mention glm...

**Comment by ericoporto** [comment]
Removed mention to alogg in Copyright page

https://github.com/adventuregamestudio/ags-manual/wiki/_compare/3c5b4e02f8e6d2d3ecec982c321e2adde6caab55...3d33ad7f15e9f1f6500dc2d290803806aced096f

**Comment by ericoporto** [comment]
Removed almp3 and aloogg, added mojoAL, SDL Sound and SDL2 in the Distributing the game licensing topic, [here's the change](https://github.com/adventuregamestudio/ags-manual/wiki/_compare/3f48c10ae53f68e05ed44b7e61dde1bb373455d8...fd3eda76704d17eda5cef06f5eb9384c82b4ee7b)

**Comment by ericoporto** [comment]
I think we don't need vorbis anymore in AGS

**Comment by ivan-mogilko** [comment]
I think this is resolved now.
