### ISSUE TITLE
[enhancement]Log of system limit changes

### ISSUE THREAD

**Issue by jumpjack** [adventuregamestudio/ags-manual#214]
My attempt to make a log of changes along versions. I based last column on current "[system limits](https://github.com/adventuregamestudio/ags-manual/wiki/SystemLimits)" page, then used various "Upgradint to V x.x.x." pages to go backwards.

I don't know if in markdown language it is possible to add colors to changed cells like I've done in excel (see screenshot).

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<body>

Feature | 3.0 | 3.1 | 3.2 | 3.3 | 3.3 | 3.3.5 | 3.4 | 3.4.1 | 3.5.0 | 3.6.0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
audio channels |   |   |   |   |   |   |   | 8 | 8 | 16
background   frames per room |   |   |   |   |   |   |   | 5 | 5 | 5
button length   limit |   |   |   |   |   |   |   | 50 | 50 | 50
characters |   |   |   |   |   |   |   | unlimited | unlimited | unlimited
character   followers |   |   |   |   |   |   |   | 30 | 30 | unlimited
controls on   each GUI |   |   |   |   |   |   |   | unlimited | unlimited | unlimited
custom   properties |   |   |   |   |   |   | 30 | unlimited | unlimited | unlimited
dialog topics |   |   |   |   |   |   |   | unlimited | unlimited | unlimited
different   script modules due to bytecode format |   |   |   |   |   |   |   | 126 | 126 | 126
DoOnceOnly   token length |   |   |   |   |   |   |   | 200 | 200 | 200
fonts |   |   |   | 15 | 30 | 30 | 30 | 30 | unlimited | unlimited
function   parameters |   |   |   |   |   |   |   | 15 | 15 | 15
GUIs |   |   |   |   |   |   |   | unlimited | unlimited | unlimited
hotspots per   room (50 with "no hotspot" area) |   |   |   |   |   |   |   | 49 | 49 | 49
listbox item   count |   |   |   |   |   |   |   | 200 | 200 | 200
sprites   (imported) |   |   |   |   |   |   |   | 30000 | 90000 | 90000
sprites   (total) |   |   |   |   |   |   |   | ? | 2 billions | 2 billions
inventory   items |   |   |   |   |   |   |   | 300 | 300 | 300
mouse cursors |   |   |   |   |   |   |   | 20 | 20 | 20
objects per   room |   |   |   |   |   |   |   | 40 | 40 | 256
options per   dialog topic |   |   |   |   |   |   |   | 30 | 30 | 30
overlays on   screen |   |   |   |   |   |   |   | 20 | 20 | unlimited
regions per   room (16 with "no region" area) |   |   |   |   |   |   |   | 15 | 15 | 15
rooms per   game, 300 of which may be state-saving (0-299) |   |   |   |   |   |   |   | 999 | 999 | 999
simultaneous   button animations |   |   |   |   |   |   |   | 15 | 15 | unlimited
textbox length |   |   |   |   |   |   |   | 200 | 200 | 200
timers |   |   |   |   |   |   |   | 20 | 20 | 20
views   (animation sets), loops in view, and frames in loop |   |   |   |   |   |   |   | unlimited | unlimited | unlimited
walkable areas   per room (16 with "non-walkable" area) |   |   |   |   |   |   |   | 15 | 15 | 15
walk-behinds   per room (16 with "no walk-behind" area) |   |   |   |   |   |   |   | 15 | 15 | 15
words in the   text parser dictionary |   |   |   |   |   |   |   | unlimited | unlimited | unlimited
local messages |   |   |   |   |   |   |   | 100 | 100 | 100
dialogs |   |   |   |   |   |   |   | ? | unlimited | unlimited
gui controls |   |   |   |   |   |   | limited ? | unlimited | unlimited | unlimited
script modules |   |   |   |   |   |   | limited ? | unlimited | unlimited | unlimited
AGS_MAX_GUIS | removed | - | - | - | - | - | - | - | - | -
AGS_MAX_CHARACTERS | removed | - | - | - | - | - | - | - | - | -
AGS_MAX_VIEWS | removed | - | - | - | - | - | - | - | - | -
AGS_MAX_LOOPS_PER_VIEW | removed | - | - | - | - | - | - | - | - | -
AGS_MAX_FRAMES_PER_LOOP | removed | - | - | - | - | - | - | - | - | -

</body>

</html>

![image](https://user-images.githubusercontent.com/1620953/212469292-36934065-806b-4bfb-940d-ea07c762c950.png)

**Comment by ericoporto** [comment]
It's better to have it as a changelog instead of a table - tables are just not good for fitting in a single page.

What is the usecase here?

**Comment by jumpjack** [comment]
History and readability.
Numbers history is better seen  in a single table than in 10 separated pages.

And I decided to download V 3.6.0 (even if not ready yet) to replace my old 3.3 right because I noticed how some limits changed/disappeared in the meantime, which are exactly the limits which prevented me from coding my game in V 3.3, and also in official latest version available (3.5).

Of course this table is not and cannot be a full changelog, it is just a "numbers changelog".

**Comment by ericoporto** [comment]
This breaks mobile, and also breaks in any export to a book format, so I won't add it. It also infinitely grows to the right - horizontal is not a good fit here. Historical notes are better in the wiki from the website or elsewhere, I don't think this is relevant to the manual. It's also incomplete information as is. 

If you can come up with another format for this information MAYBE it's possible to add in the manual but I am against - I believe we should always move forward.

I would advise holding this information elsewhere.

**Comment by ivan-mogilko** [comment]
> Historical notes are better in the wiki from the website or elsewhere, I don't think this is relevant to the manual.

Then why do we have a ["Changelog of lifted limits"](https://github.com/adventuregamestudio/ags-manual/wiki/SystemLimits#changelog-of-lifted-limits) section in this page then? Maybe we should remove it altogether?

**Comment by ivan-mogilko** [comment]
By the way, something that I keep forgetting about, but there's one unfortunate issue with the system limits at the moment.
Because of how the manual building is set up, same source is used to build the manual for any release. So when, for example, I release patches for 3.5.1, it also gets same contents as 3.6.0.

The script API articles have "Compatibility" notes, telling which version this API is available from. But system limits don't have any such distinction.

**Comment by jumpjack** [comment]
> > Historical notes are better in the wiki from the website or elsewhere, I don't think this is relevant to the manual.
> 
> Then why do we have a ["Changelog of lifted limits"](https://github.com/adventuregamestudio/ags-manual/wiki/SystemLimits#changelog-of-lifted-limits) section in this page? Maybe we should remove it altogether?

sorry for my english but with ""lifted" do you mean "increased" or "removed"?
And which were the previous limits for sprites now increased to 2bln?

**Comment by ivan-mogilko** [comment]
> sorry for my english but with ""lifted" do you mean "increased" or "removed"?

It was not me who wrote that, but I guess it is supposed to mean "increased".

> And which were the previous limits for sprites now increased to 2bln?

IIRC total number of sprites were limited to 30k in the past, that included both imported and dynamic sprites together.

**Comment by ivan-mogilko** [comment]
I decided to make an experiment, and created a "limited" table, only refering to the last 3 versions of AGS:
https://github.com/adventuregamestudio/ags-manual/wiki/SystemLimits

If others will think that's ugly, it may be reverted / rewritten; but I wanted to make this as a test.

Also removed "Changelog of lifted limits" section, because I also don't think it belongs to this particular article.
My understanding on this article is that it should give a quick reference of "what current version can do".
Maybe I am wrong, but then we'd need to clarify its purpose. Also, we are writing this manual for users, so it may be interesting to know which information *they* are looking for.

As for having a bigger history of changes, starting from early versions, my opinion is following:
Such information is definitely useful as a historical record, and when diagnosing problems in older versions. Not everyone uses latest versions of AGS at all times. Often people begin making game in particular version of the editor, and keep using same version without updating, until the game is released, which may take years. So having a "knowledge base", which would contain such records, including information about various "quirks", may come useful sometimes.
But I have doubts that such records should be located in this user manual, as its primary purpose is documenting latest version.

Perhaps we could open a separate repository for the "knowledge base" elsewhere.

**Comment by jumpjack** [comment]
Another possibility could be to write in SystemLimits page just current limits, and add a link "see also 'System limits history'" at bottom of page.

Some notes:
 - at a first glance I didn't understand why some values were marked as "less than (<)"....  :-)  I think it would be better to just repeat the values, given that changes are highlighted in bold.
 - table should be sorted
 - items listed should be easily found, so it should be defined a "resource name pattern" like "item name (adjectives/notes)"; hence, rather than "total rooms per game" it should read "rooms per game", "custom properties" should read "properties (custom)", "Imported sprites" and "Dynamic sprites" should read "sprites (imported)", and "sprites (dynamic)"; in other words, first word should be a noun, not an adjective.

Also a link "See also '[Used resources](https://adventuregamestudio.github.io/ags-manual/Globalfunctions_General.html?#getgameparameter)'" could be useful, together with "See also 'Game functions and properties'"" at the beginning of "Room page".

**Comment by jumpjack** [comment]
By the way, I see that currently only 4 of these limits:

- AGS_MAX_INV_ITEMS	The maximum number of inventory items
- AGS_MAX_OBJECTS	The maximum objects per room
- AGS_MAX_HOTSPOTS	The maximum hotspots per room
- AGS_MAX_REGIONS	The maximum regions per room

**Comment by jumpjack** [comment]
About the float: some days ago I edit the wiki page adding the result of my study, which revealed how a float can hold values from -2^127 to 2^127... but probably I edited another version of the wiki, so I cannot find my edit anymore anywhere...

But there is a problem: due to limits of IEE754 float, a 32 bit float cannot represent all integers between, for example, 2^126 and 2^127, because "A 32 bit [float](https://en.wikipedia.org/wiki/Single-precision_floating-point_format) can't have enough precision to store the exact value of a 32 bit unsigned int because the significant precision is only 24 bits. " ( https://stackoverflow.com/questions/36535278/error-on-converting-from-unsigned-int-to-float#comment60674533_36535278 )

So "integer by float" continuity stops at 16777216.0000: next "int by float" is 16777218.0000.


Some test code (look into your "saved games" folder for output):

 ```

function debugPrint(String text,  bool displ) { 
  File *output = File.Open("$SAVEGAMEDIR$/log.txt", eFileAppend);
  if (output == null)
    Display("Error writing to log file.");
  else {
    DateTime *dt = DateTime.Now;
    String dateText = String.Format("%4d/%02d/%02d %02d:%02d:%02d" , dt.Year, dt.Month, dt.DayOfMonth,  dt.Hour,  dt.Minute,  dt.Second);
    String filetext = dateText.Append(" - ");
    filetext = filetext.Append(text);
    output.WriteRawLine(filetext);       
    output.Close();
    CL_Console.Log(text);
    if (displ) { // blocking message
        Display(filetext);
    }
  }
 }


for (int i = 1; i < 128; i++) {
    debugPrint(String.Format("i,f: %d, %.0f, %.0f",  i,  Maths.RaiseToPower(2.0, IntToFloat(i)) ,  -Maths.RaiseToPower(2.0, IntToFloat(i))) ,  false);   
  }

float temp;
for (int i = 1; i < 513; i++) {
    temp =   Maths.RaiseToPower(2.0, IntToFloat(32)) + IntToFloat(i);
    debugPrint(String.Format("i,f: %d, %f, %f",  i, Maths.RaiseToPower(2.0, IntToFloat(32)),  temp),    false);   
  }
  temp = 4294967296.0 + 1.0;
  debugPrint(String.Format("4294967296.0 + 1.0:  %f",  temp),    false);   
  temp = 4294967296.0 + 2.0;
  debugPrint(String.Format("4294967296.0 + 2.0:  %f",  temp),    false);   
  temp = 4294967296.0 + 255.0;
  debugPrint(String.Format("4294967296.0 + 255.0:  %f",  temp),    false);   
  temp = 4294967296.0 + 256.0;
  debugPrint(String.Format("4294967296.0 + 256.0:  %f",  temp),    false);   
  temp = 4294967296.0 + 257.0;
  debugPrint(String.Format("4294967296.0 + 257.0:  %f",  temp),    false);   
 
 for (int i = 1; i < 100; i++) {
    temp =   Maths.RaiseToPower(2.0, IntToFloat(23)) + IntToFloat(i);
    debugPrint(String.Format("i,f: %d, %f, %f",  i, Maths.RaiseToPower(2.0, IntToFloat(23)),  temp),    false);   
  }
  
float base =  2.0 * Maths.RaiseToPower(2.0, IntToFloat(23))  - 50.0 ;
for (int i = 1; i < 100; i++) {
    temp =   base + IntToFloat(i);
    debugPrint(String.Format("%d, %f,  %f",  i, base,  temp ) ,  false);   
  }  
```

**Comment by ivan-mogilko** [comment]
> About the float: some days ago I edit the wiki page adding the result of my study, which revealed how a float can hold values from -2^127 to 2^127... but probably I edited another version of the wiki, so I cannot find my edit anymore anywhere...

We removed that text, because it contained dubious information, and also alot of unnecessary print logs.
Then added part of the text back, fixing the info.
Current information is based on wikipedia article and certain discussion on stackoverflow: 
https://stackoverflow.com/questions/3793838/which-is-the-first-integer-that-an-ieee-754-float-is-incapable-of-representing-e

**Comment by ivan-mogilko** [comment]
> * at a first glance I didn't understand why some values were marked as "less than (<)"....  :-)  I think it would be better to just repeat the values, given that changes are highlighted in bold.
> * table should be sorted
> * items listed should be easily found, so it should be defined a "resource name pattern" like "item name (adjectives/notes)"; hence, rather than "total rooms per game" it should read "rooms per game", "custom properties" should read "properties (custom)", "Imported sprites" and "Dynamic sprites" should read "sprites (imported)", and "sprites (dynamic)"; in other words, first word should be a noun, not an adjective.
> 
> Also a couple of links "See also '[Used resources](https://adventuregamestudio.github.io/ags-manual/Globalfunctions_General.html?#getgameparameter)'" and "See also ''[System constants](https://adventuregamestudio.github.io/ags-manual/Constants.html)'" could be useful, together with "See also 'Game functions and properties'"" at the beginning of "Room page".

Mostly done this, except kept "Custom properties" name, as this is a well defined term in AGS (other properties cannot be  limited in principle).

I shall close this ticket; like was said, the full history of changes is best to be placed in some kind of a "Knowledge base", if somebody will make such.
