### ISSUE TITLE
[3.6.1] Script API: document ScriptName and GetByName

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#229]
From [forums ](https://www.adventuregamestudio.co.uk/forums/ags-engine-editor-releases/ags-3-6-1-beta/msg636657662/#msg636657662)

> Script API:
> - Added ScriptName property to AudioClip, Character, Dialog, GUI, GUIObject, Hotspot, InventoryItem, Object.
> - Added static GetByName() function to AudioClip, Character, Dialog, GUI, GUIObject, Hotspot, InventoryItem, Object.

These need to be written and GetByName needs example

- [x] Character
- [x] GUI
- [x] Dialog
- [x] GUIControl
- [x] Hotspot
- [x] InventoryItem
- [x] AudioClip
- [x] Object

**Comment by ivan-mogilko** [comment]
> These need to be written and GetByName needs example

I suppose the good examples are the ones where you cannot save object links as a pointer, but do not want to use numeric IDs:
- custom properties
- writing and reading custom files, where you save some properties for object

**Comment by ericoporto** [comment]
That is an interesting point, these are indeed very interesting when serializing/deserializing data that is relational, specifically better if you want to make the data easier to read - maybe for debug purposes.

Other idea is to make sure data is independent of the ID (in case it changes), I guess this somehow the point @messengerbag was trying to make [here](https://www.adventuregamestudio.co.uk/forums/advanced-technical-forum/portable-save-game-module-discussion/msg636573643/#msg636573643)

Anyway, I am even more curious now about writing that save game module idea I had in the past.

For now I am trying to think about some small example, maybe I will look in small relational db examples and then figure something up from this. :)

**Comment by ivan-mogilko** [comment]
I mean, something like

```
cChar1.SetTextProperty("MyFriend", cChar2.ScriptName);

Character *myfriend = Character.GetByName( cChar1.GetTextProperty("MyFriend") );
```

**Comment by ericoporto** [comment]
Wrote something for Objects here

https://github.com/adventuregamestudio/ags-manual/wiki/Object/_compare/a4d7dab%5E...a4d7dab

**Comment by ivan-mogilko** [comment]
I think there is an issue with phrasing there:
> if the room has an object the player haunts
this means that the player haunts the object?

**Comment by ericoporto** [comment]
> this means that the player haunts the object?

I need to think on a different example there that is simpler to understand. In my head the idea was like, if a room has an object of name X, then something special can happen with that object provided some condition, but this may be too complicated.

---

Wrote something simpler for AudioClip https://github.com/adventuregamestudio/ags-manual/wiki/AudioClip/_compare/c7fb66e%5E...c7fb66e

I will stop now on these and think a little more before continuing on the others.

**Comment by ericoporto** [comment]
Added Inventory Item GetByName and ScriptName: https://github.com/adventuregamestudio/ags-manual/wiki/InventoryItem/_compare/1f45ede%5E...1f45ede

**Comment by ericoporto** [comment]
Added Hotspot GetByName and ScriptName: https://github.com/adventuregamestudio/ags-manual/wiki/Hotspot/_compare/9ce2797%5E...9ce2797

The first example I got no ideas to what to do, so it's a terrible one, ideas to improve are welcome

**Comment by ericoporto** [comment]
added GUI Control GetByName and ScriptName: https://github.com/adventuregamestudio/ags-manual/wiki/GUIControl/_compare/788176e%5E...788176e

**Comment by ericoporto** [comment]
added Dialog GetByName and ScriptName: https://github.com/adventuregamestudio/ags-manual/wiki/Dialog/_compare/51512bb%5E...51512bb

My examples were very lazy here...

**Comment by ivan-mogilko** [comment]
Added where missing, made descriptions uniform, and more varied examples.
