### ISSUE TITLE
[3.6.1] Interaction callbacks: new parameters 

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#230]
Script API:
- Expanded interaction functions for Character, Object, InventoryItem, Hotspot and Region types: now they all receive respective object's pointer as a parameter, similar to GUI event functions, as well as a cursor mode this interaction was run with, if applicable.

> Regarding expanded interaction functions, these are functions connected to Look at, Interact, Talk to and other similar events. They all now may have 2 parameters: a pointer to object, and cursor mode, similar to the following examples:
> ```AGS Script
> function Ego_Interact(Character *c, CursorMode mode)
> function oObject1_Look(Object *o, CursorMode mode)
> ```
> 
> Exceptions:
> - Hotspot WalkOn and MouseOver events do not have CursorMode parameter.
> - All Region events do not have CursorMode parameter.
> 
> The purpose of this addition is to improve situation where you connect same function to multiple events and/or multiple objects at once. In such case you will be able to distinguish object and mode for which the function is actually called.
> 
> These new parameters are optional. If you don't have them declared in script, they will be ignored by the engine, and your script is going to run as before.

From [forums](https://www.adventuregamestudio.co.uk/forums/ags-engine-editor-releases/ags-3-6-1-beta/msg636656676/#msg636656676)

**Comment by ericoporto** [comment]
These interactions and events in general are described here: [EventTypes](https://github.com/adventuregamestudio/ags-manual/wiki/EventTypes).

This file is directly linked from [Home](https://github.com/adventuregamestudio/ags-manual/wiki/Home).

I think maybe the format of this file could be improved somehow, there are six things with their events described in the file:

- Hotspot Events
- Object Events
- Room Events
- Inventory Item Events
- Character Events
- Region Events

I was thinking in keeping it as a master file and breaking the others to their own files, having each event as a heading. Or just having each event as h4 type of heading - we only use those in the tutorials and in the engine plugin api description.

**Comment by ivan-mogilko** [comment]
The event functions are also mentioned in the tutorial, on these pages:
https://github.com/adventuregamestudio/ags-manual/wiki/acintro3
https://github.com/adventuregamestudio/ags-manual/wiki/acintro4
https://github.com/adventuregamestudio/ags-manual/wiki/acintro5
https://github.com/adventuregamestudio/ags-manual/wiki/acintro7
https://github.com/adventuregamestudio/ags-manual/wiki/acintro8
some of these are present as a code, but some unfortunately are on a screenshot...

**Comment by ivan-mogilko** [comment]
Updated and reorganized Event Types topic:
https://github.com/adventuregamestudio/ags-manual/wiki/EventTypes/_compare/bf1c874955ec8faa59ba0bccaed47943ec941bba...391ae7ebb78ba32f72bbca482f12fe2c757ceb7b

I think that will do for now, but of course the topic may be improved further.
