### ISSUE TITLE
Runtime config reference not synced with the 3.6.0 engine

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#234]
Somehow this is still missing few newer options.

"[graphics] window", "[graphics] fullscreen", and maybe anything else
https://github.com/adventuregamestudio/ags/blob/release-3.6.0/OPTIONS.md

EDIT: also "[misc] titletext".

**Comment by ericoporto** [comment]
added graphics window and fullscreen here: https://github.com/adventuregamestudio/ags-manual/wiki/EngineConfigFile/_compare/2ffa4e9%5E...2ffa4e9

**Comment by ivan-mogilko** [comment]
I'd like to double check.

**Comment by ivan-mogilko** [comment]
Okay, seems to match now; I also had to remove few old options remaining since pre-3.6.0 times.
https://github.com/adventuregamestudio/ags-manual/wiki/EngineConfigFile/_compare/821f1c041245a377b411026f4b00705a5c57289d...3829feefea8a75e612d56990252771ec44447626

**Comment by Crystal-Shard** [comment]
Where it says that options are locked in a default state, does that mean the AGS default (similar to if the option was not in the cfg file) or does it mean whatever is stated in the cfg file?

**Comment by ivan-mogilko** [comment]
> Where it says that options are locked in a default state, does that mean the AGS default (similar to if the option was not in the cfg file) or does it mean whatever is stated in the cfg file?

The option set in cfg file.

**Comment by Crystal-Shard** [comment]
> > Where it says that options are locked in a default state, does that mean the AGS default (similar to if the option was not in the cfg file) or does it mean whatever is stated in the cfg file?
> The option set in cfg file.

Maybe the manual could indicate that?

**Comment by ivan-mogilko** [comment]
Does it look better now?
https://github.com/adventuregamestudio/ags-manual/wiki/EngineConfigFile/_compare/3829feefea8a75e612d56990252771ec44447626...45961828944035911b7e467478b5ab9409c5e9a7

**Comment by Crystal-Shard** [comment]
Looks good to me!
