### ISSUE TITLE
[3.6.0] "Gui control clip their contents" is not mentioned in General Settings

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#236]
Need to add this property, and also since at that double check that the General Settings page reflect 3.6.0 overall.

**Comment by ericoporto** [comment]
just to keep track of changes, about "Gui control clip their contents", you added right now here

https://github.com/adventuregamestudio/ags-manual/wiki/GeneralSettings/_compare/f16525b%5E...f16525b

**Comment by ivan-mogilko** [comment]
I'm running through the list of options now, looks like few backward options have changed their place in the table, and few others may benefit from adding more details to them.

**Comment by ivan-mogilko** [comment]
Okay, I guess i'm done.
https://github.com/adventuregamestudio/ags-manual/wiki/GeneralSettings/_compare/eb972118f97fc078e7242e23ebb44effc1b5cebe...5da3eef63e4ed451989eda5ceac9dc8cbcb5f6c2
