### ISSUE TITLE
Document /compile, and any other cmdline options if they exist

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#237]
Perhaps have a "Command line arguments" under Editor section, or "Editor -> Other features" for now. That's a quickest solution.

Alternatively, make a topic on automatic building and using tools (but we don't have a full tool set for making whole game yet).

**Comment by ericoporto** [comment]
added it in [Editor Command Line Options](https://github.com/adventuregamestudio/ags-manual/wiki/EditorCommandLineOptions), and added it in Other Features [here](https://github.com/adventuregamestudio/ags-manual/wiki/OtherFeatures/_compare/a7a8cac%5E...a7a8cac).
