### ISSUE TITLE
Document where engine plugins should be placed in the Editor's folder

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#238]
There's an article on Plugins which briefly explains where plugins has to be placed, but it does not cover all the platforms.
https://github.com/adventuregamestudio/ags-manual/wiki/Plugins

Need to make a distinct section in the article and explain where the plugins should go for each supported build target.

**Comment by ericoporto** [comment]
added a new sub entry here

https://github.com/adventuregamestudio/ags-manual/wiki/Plugins/_compare/5cf0318%5E...5cf0318
