### ISSUE TITLE
 Add miniz on licensing

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#240]
Add miniz licensing info here https://github.com/adventuregamestudio/ags-manual/wiki/Copyright

**Comment by ivan-mogilko** [comment]
Ah, there's also
https://github.com/adventuregamestudio/ags-manual/wiki/Credits that has license info

**Comment by ericoporto** [comment]
> Is this fine?

Looks fine, saw you already added in Credits, let's close this.
