### ISSUE TITLE
Document added global events

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#256]
https://github.com/adventuregamestudio/ags-manual/wiki/Globalfunctions_Event#on_event

The following events were added in 3.6.2

```
eEventDialogStart 
- arg1 means dialog ID
```
```
eEventDialogStop
 - arg1 means dialog ID
```
```
eEventDialogRun
- arg1 is dialog ID, arg2 is entry ID, where starting entry (@S) is 0, and user-made options begin with 1
- triggers whenever a dialog entry is run
```
```
eEventDialogOptionsOpen
 - triggers whenever dialog options are shown
```
```
eEventDialogOptionsClose
- triggers whenever dialog options are hidden
```

There is an example using all of these in the demo game [362--demo-dialogevents.zip](https://github.com/user-attachments/files/17831414/362--demo-dialogevents.zip).
<details>
<summary>The code in this game is the one hidden here</summary>

```
function on_event(EventType evt, int data1, int data2)
{
  /**/
  if (evt == eEventDialogStart)
  {
    gIconbar.Visible = false;
    gStatusline.Visible = false;
    gDialogOverlay.Visible = true;
    btnOptionName.Visible = false;
    btnSelectOption.Visible = false;
  }
  else if (evt == eEventDialogStop)
  {
    gDialogOverlay.Visible = false;
    gIconbar.Visible = true;
    gStatusline.Visible = true;
  }
  else if (evt == eEventDialogOptionsOpen)
  {
    btnSelectOption.Visible = true;
    btnOptionName.Visible = false;
  }
  else if (evt == eEventDialogOptionsClose)
  {
    btnSelectOption.Visible = false;
  }
  else if (evt == eEventDialogRun)
  {
    btnDialogName.Text = dialog[data1].ScriptName;
    btnOptionName.Visible = true;
    if (data2 == 0)
      btnOptionName.Text = "starting conversation...";
    else
      btnOptionName.Text = dialog[data1].GetOptionText(data2);
  }
  /**/
}

function repeatedly_execute_always()
{
  Dialog* dlg = Dialog.CurrentDialog;
  if (dlg == null)
    lblDialogNow.Text = "NO";
  else
    lblDialogNow.Text = dlg.ScriptName;
  
  int option = Dialog.ExecutedOption;
  if (option < 0)
    lblExeOption.Text = "NO";
  else
    lblExeOption.Text = String.Format("%d", option);

  if (Dialog.AreOptionsDisplayed)
    lblAreOptions.Text = "DISPLAYED";
  else
    lblAreOptions.Text = "HIDDEN";
}
```

</details>

The way the session is currently there is no space for examples.

These events do allow to do things like, playing a sound when dialog options are shown, or showing and hiding a GUI for a screen border when the game is in "dialog mode", having a particular background music for a dialog option, ... 

Description from the forums

> 
> All of these events are handled in "on_event" function:
> eEventDialogStart - arg1 means dialog ID
> eEventDialogStop - arg1 means dialog ID
> eEventDialogRun - triggers whenever a dialog entry is run, arg1 is dialog ID, arg2 is entry ID, where starting entry (`@S`) is 0, and user-made options begin with 1
> eEventDialogOptionsOpen - triggers whenever dialog options are shown
> eEventDialogOptionsClose - triggers whenever dialog options are hidden
>

**Comment by ivan-mogilko** [comment]
Some notes.

eEventDialogStart is run only once the dialog state is started, but not when another topic is run from within the dialog script. The latter may be detected by eEventDialogRun with different dialog ID and entry id = 0.

eEventDialogStop reports the last dialog id before exiting dialog state, which may be different from the one in eEventDialogStart.

**Comment by ericoporto** [comment]
added 
https://github.com/adventuregamestudio/ags-manual/wiki/_compare/8d608c1cbb38faac62dd1dd1715aaf197b25f191...11b1bd953590b5b93975e7b7ca9b34eb3dd8c71f
