### ISSUE TITLE
Document DynamicSprite CreateFromScreenShot render layer parameters

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#258]
https://github.com/adventuregamestudio/ags-manual/wiki/DynamicSprite#dynamicspritecreatefromscreenshot

```
  /// Creates a dynamic sprite as a copy of the current screen.
  import static DynamicSprite* CreateFromScreenShot(int width=0, int height=0, int layer=eRenderLayerAll);  // $AUTOCOMPLETESTATICONLY$
```

need to explain that the parameter `int layer` is to be used like flags of the RenderLayer enum, which accepts either any or a boolean combination of them. See https://adventuregamestudio.github.io/ags-manual/Globalfunctions_Wait.html?highlight=waitinput&case_sensitive=0#waitinput for an example.

The RenderLayer enum should be documented too in standard enums, see #259

---

@ivan-mogilko  should the layer parameter be of the type RenderLayer like in the case of WaitInput ?

**Comment by ivan-mogilko** [comment]
> @ivan-mogilko should the layer parameter be of the type RenderLayer like in the case of WaitInput ?

Yes, that parameter may be changed to the enum.

**Comment by ericoporto** [comment]
ok, changed to RenderLayer https://github.com/adventuregamestudio/ags/commit/7ca3527cf3b169e4e1f8d2e6b313f97465769aab

**Comment by ericoporto** [comment]
documented it here
https://github.com/adventuregamestudio/ags-manual/wiki/_compare/d2510282950689068dbf56ad8c9bff15cd212dfb...dcb5c02593291b831ed8c493d5f708db63861531
