### ISSUE TITLE
Document added System entries (GetEngineInteger and GetEngineString)

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#260]
https://github.com/adventuregamestudio/ags-manual/wiki/System

```
  /// Gets a runtime engine value represented as integer by the given identifier; is meant for diagnostic purposes only
  import static int GetEngineInteger(EngineValueID value, int index = 0); // $AUTOCOMPLETESTATICONLY$
  /// Gets a runtime engine string by the given identifier; is meant for diagnostic purposes only
  import static String GetEngineString(EngineValueID value, int index = 0); // $AUTOCOMPLETESTATICONLY$
```

Examples of using it

```
int spritecachemax = System.GetEngineInteger(ENGINE_VALUE_I_SPRCACHE_MAXNORMAL);
int spritecachecurrent = System.GetEngineInteger(ENGINE_VALUE_I_SPRCACHE_NORMAL);
int spritecachepercent = spritecachecurrent * 100 / spritecachemax;
lblInfo.Text = String.Format("Sprite cache: %d / %d (%d%%)", spritecachecurrent, spritecachemax, spritecachepercent);
```

These were originally added in this PR https://github.com/adventuregamestudio/ags/pull/2358

The enums are documented in #259

**Comment by ericoporto** [comment]
after this is in, put mention of it from `System.DisplayFPS` entry

**Comment by ivan-mogilko** [comment]
Added these:
https://github.com/adventuregamestudio/ags-manual/wiki/System#systemgetengineinteger

**Comment by ericoporto** [comment]
@ivan-mogilko we don't actually have any II (indexed integer) enums, do we?

**Comment by ivan-mogilko** [comment]
> @ivan-mogilko we don't actually have any II (indexed integer) enums, do we?

Not right now, but this signature is reserved for that purpose.

**Comment by ericoporto** [comment]
I think it is better to either remove it or make a note that none of those are there yet, otherwise it looks like at least one of the enums must be a typo.

**Comment by ivan-mogilko** [comment]
Why remove it? It's a future compatible specification. We are saying that if such value IDs will be added, then they will use this pattern. It's a normal thing for expandable API, imo.

**Comment by ericoporto** [comment]
ok. Closing this as it is done.
