### ISSUE TITLE
Importing plugins/scripts

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags-manual#27]
The manual [entry about plugins](https://github.com/adventuregamestudio/ags-manual/wiki/Plugins) is outdated in two major points:
1) when it mentions "AGSEDIT", this was the old editor's name.
2) it does not tell how to deal with plugins when you port your game to other systems.

Also, I could not find any information about importing script modules in the manual. Need to make sure one exists and is up-to-date.

**Comment by ericoporto** [comment]
Updated the wiki a bit to refer to the current editor, pointed a normal folder (if the person Installed AGS) and added an image on how to activate the plugin.

> it does not tell how to deal with plugins when you port your game to other systems.

I noticed that if I build to Linux it complains about that, I instead now only build the Windows and Data and manually add the engine in the Data folder, since doing that won't get the engine rewritten, or any plugins. Also only engine plugins are relevant regarding ports. Speech Center for example, is an Editor plugin, and doesn't care for where the Engine runs.

**Comment by ericoporto** [comment]
I added a small entry on how to do it for linux [0c2232b](https://github.com/adventuregamestudio/ags-manual/wiki/Plugins/_compare/cee658222ddccc3a0e9e5d6e6f182d148d81e142...0c2232b5df001e08fd391ec86722ca214521ba7a).

**Comment by ericoporto** [comment]
Created a possible entry for a Script Modules page to be added under [Other Features](https://github.com/adventuregamestudio/ags-manual/wiki/OtherFeatures)

---

# Script Modules

AGS script modules are a way for AGS script code to be reused and shared. They are written in AGS script code entirely, and thus are independent of the platform on which a game is run.

A Script Module is a pair of an AGS Script file and an AGS Script Header file, with an additional metadata.

## Managing modules

You can manage them by expanding the Script entry in the tree of Explore Project panel.

You can right click to show options

- **New script**
  - create a new module from scratch
- **Import script...**
  - load a module from a `.scm` file that you have downloaded
- **New folder**
  - creates folder, which can be used to organize script modules in groups
  
When you click a module directly, you can use the properties panel to enter a brief description of the module, a version number and authorship details in the module manager when you create a module. Double clicking will expand and revel both the
script and the header files.

Right clicking the module should give you the options:

- **Rename**
  - Give the module another name
- **Delete**
  - Removes an existing module from the game
- **Move up**
  - The order of modules can be important, as it reflects the order in which they are compiled and run, so this option and the next let you change their ordering.
- **Move down**
  - moves the script module up in the order
- **Export...**
  - save your own module as a `.scm` file that you can share with others

You can find useful script modules from others in the [Modules & Plugins board](https://www.adventuregamestudio.co.uk/forums/index.php?board=10.0) in the ags forums.

**Comment by ericoporto** [comment]
@morganwillcock I would like your feedback on adding this Script Modules topic. :)

**Comment by morganwillcock** [comment]
The 'move up' and 'move down' menu items only seem to appear when you right click a folder, right-clicking a module doesn't give the movement options. I'm not sure why there is a distinction between the two, but when I've tried it seems the only way to change the ordering is to drag them on top of each other.

On the plus side the behaviour is so unintuitive and unfriendly to the user that I can easily state that the information must go into the manual. I would say that the impact of ordering on script compilation and execution is probably the most critical part, so an example of the correct order for two example script modules would be good.

**Comment by ericoporto** [comment]
Hey @morganwillcock I updated the entry above.

I was going to add the entry but I noticed I had already added a ScriptModules entry!

It's here -> https://github.com/adventuregamestudio/ags-manual/wiki/ScriptModules

It's referenced here, as "Multiple Scripts" -> https://github.com/adventuregamestudio/ags-manual/wiki/ScriptingLanguage

I am unsure how to best proceed now.

**Comment by ivan-mogilko** [comment]
IMHO the above entry is meant for the Editor chapter, as it explains the method of managing scripts in the editor's project tree.

**Comment by morganwillcock** [comment]
As long as the page is not orphaned and the links to the page are also modified, everything should keep working. In theory a broken link is caught by `make metacheck` but there are no checks for orphaned pages.

**Comment by ivan-mogilko** [comment]
Plugins topic was updated a while ago, and now added @ericoporto 's article (here)[ScriptModules]
