### ISSUE TITLE
Document on_mouse_click extra parameters

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#275]
https://github.com/adventuregamestudio/ags-manual/wiki/Globalfunctions_Event#on_mouse_click

Expanded on_mouse_click callback, now supports two more parameters: click x,y coordinates.

it now is `void on_mouse_click (MouseButton button, int mx, int my)`.

from PR https://github.com/adventuregamestudio/ags/pull/2470, and commit https://github.com/adventuregamestudio/ags/commit/11f0247aeab7a9d8ca17f3e460195a3fae2c8b60

**Comment by ivan-mogilko** [comment]
Added them.
