### ISSUE TITLE
Document dialog_options_mouse_click extra parameters

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#276]
https://github.com/adventuregamestudio/ags-manual/wiki/CustomDialogOptions

```AGS Script
void dialog_options_mouse_click(DialogOptionsRenderingInfo *info, MouseButton button, int mx, int my)
```

- Added in PR https://github.com/adventuregamestudio/ags/pull/2470,
- Commit https://github.com/adventuregamestudio/ags/pull/2470/commits/2d9846ae7a80ef54e4b631b4cd54a00904da1183

**Comment by ivan-mogilko** [comment]
Added them.
