### ISSUE TITLE
Edit all references to the "default" template

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags-manual#33]
https://www.adventuregamestudio.co.uk/forums/index.php?topic=56583.0
> The in-game help still tells the user to start with the "default" template.

**Comment by morganwillcock** [comment]
I only had a quick look, but is seems to be in there.

```
$ grep -R "Default Game" .
./Templates.md:- [Default Game]
./acintro1.md:The "Default Game" template is what we'll be using, as it comes with
./acintro1.md:So, select "Default Game" and click Next.
```

**Comment by ivan-mogilko** [comment]
I see, these changes were made in ags.tex but not copied to this repository.

**Comment by ivan-mogilko** [comment]
Hmm, yes, this is awkward.

Is it safe to take ags-help.chm posted here for the use in releases? I recall there was some problem with index earlier but did not know whether it was resolved.

If it's okay to use these CHMs now, I will delete ags.tex from main repository and only edit here from now on.

**Comment by morganwillcock** [comment]
I don't think anyone has 100% confirmed that the index lookups are working for everything in the Editor, so I'd be more inclined to stick with the old manual for current release.

**Comment by ivan-mogilko** [comment]
Alright, I will try to get desynced changes to this repository then.

**Comment by ivan-mogilko** [comment]
I copied changes from main repo: 0c0d9c9ac4c51811181253156d06eb857400bd6f

**Comment by morganwillcock** [comment]
I've added one final change (commit a6ce45656d2896ee66b6537e5cf51b146169b924) which I'll also submit for the old manual.
