### ISSUE TITLE
Disable highlighting in code blocks

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags-manual#34]
Unfortunately, I think m2r internals are overriding all code blocks to have the Sphinx build guess the language in each block:
```def block_code(self, code, lang=None):
    if lang == 'math':
        first_line = '\n.. math::\n\n'
    elif lang:
        first_line = '\n.. code-block:: {}\n\n'.format(lang)
    elif _is_sphinx:
        first_line = '\n.. code-block:: guess\n\n'
    else:
        first_line = '\n.. code-block::\n\n'
```

...and this seems to override the Sphinx option `highlight_language`. So at the moment, some code blocks have no highlighting, whereas others have incorrect highlighting (mistakenly matched against another language), and we cannot disable it.

**Comment by morganwillcock** [comment]
I've submitted a change to m2r to just return a literal block (no language specified), so that Sphinx can then manage the highlight language.

https://github.com/miyakogi/m2r/pull/30

**Comment by ericoporto** [comment]
Closing because this is fixed by the new manual assembly through pandoc.
