### ISSUE TITLE
on page links / anchor links don't work on the web version

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags-manual#35]
Do I understand correctly, that the page https://adventuregamestudio.github.io/ags-manual/Game.html for example is generated from this wiki here?

on this page all the 
_See also:_
links linking to another paragraph on the very same page don't work. Within the wiki version on this part of github it works. Or are these 2 manuals separate from eachother? Then the links still don't work.

**Comment by ericoporto** [comment]
Apparently sphinx is eating the anchors :/

**Comment by morganwillcock** [comment]
Apparently this is correct according to the spec, and these are lost in m2r during conversion to reST (where there is no support for internal links using url fragments). We could possibly force the links to be treated as external, or patch m2r to force the links in, but...

...to be honest, [Doxygen](http://doxygen.nl/) is looking a better bet than Sphinx, so now we've got a working CHM compiler and are aware of indexing issues I'll probably give it a try and see if the result is any better.

**Comment by ericoporto** [comment]
Ok, Doxygen also theoretically supports building the project files that enable `.chm` build. Here is the entry in it's manual -> http://www.doxygen.nl/manual/config.html#cfg_generate_htmlhelp

**Comment by morganwillcock** [comment]
Doxygen has automatic conversion of headings to hierarchical sections, but unfortunately it is only used for the table of contents and the actual indexing is just a flat document list (so pressing F1 in the script editor doesn't work). Maybe I've missed an option, so will keep looking; everything else was working.

**Comment by ericoporto** [comment]
@selmiak the manual has a new build system made by @morganwillcock , this should now be fixed! If you confirm it is, I will close this.

**Comment by selmiak** [comment]
take my thumbs up you sleaky wizards, it works! Horray!

**Comment by ericoporto** [comment]
Thanks for reviewing @selmiak! I am closing this.
