### ISSUE TITLE
[Discussion] Game variables

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#36]
source is [Gamevariables.md](https://github.com/adventuregamestudio/ags-manual/wiki/Gamevariables).
###

I noticed some references to resolutions

> | variable | description |
> | ------------ | ------------- |
> | ... | ... |
> | game.screenshot_height | The height of screenshot images when saved into save games. The largest you can have is the full screen size (***320x200***), which gives the highest quality but the largest size save game files. The default is ***160x100***. |
> | game.screenshot_width | The width of screenshot images when saved into save games. |

Need to figure out if this defaults are true or if this was updated to be whatever the game resolution is.

**Comment by ivan-mogilko** [comment]
Yes, defaults are 160x100, minimal supported value is 16x16, maximal is game native resolution.

**Comment by ericoporto** [comment]
Ok, just changed the 320x200 for Game resolution.

**Comment by selmiak** [comment]
is there any reason why height is listed before width?
For webdevelopers it's always width, then height. 

This is also in the properties for GUIs I think, but this is an issue for AGS itself not the manual, here I ask just for the order of these 2 manual entries.

**Comment by ericoporto** [comment]
Probably because the alphabet has h before w.

**Comment by selmiak** [comment]
That is a valid reason, still confusing in my opinion...

**Comment by ivan-mogilko** [comment]
All the variables in the list are in alphabet order, from start to finish, it just happened by coincidence that two of them form width/height pair.
