### ISSUE TITLE
[Discussion] System functions and properties

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#37]
source is System.md.
###

For [System.HardwareAcceleration](https://adventuregamestudio.github.io/ags-manual/System.html?highlight=system#hardwareacceleration), I believe it also returns True when the game is running on OpenGL on Windows, Linux or Android. Need to check and fix the table shown. Currently, it's as below

> **Cross-Platform Support**
> 
> Windows: **Direct3D driver**
> MS-DOS: **No**
> Linux: **No**
> MacOS: **No**

**Comment by ivan-mogilko** [comment]
Right, this should also relate to OpenGL.

**Comment by ericoporto** [comment]
Updated the entry.
