### ISSUE TITLE
Multiplatform references

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags-manual#38]
Whenever the systems are mentioned, their list should be adjusted to current situation:

* Any references to MS-DOS should be removed (we no longer support it);
* Systems supported now (more and less): Windows, Linux, Mac OSX, Android, iOS;
* PSP should not be mentioned because the future of this port is unclear.

**Comment by sonneveld** [comment]
I suggest removing PSP support. SDL2 doesn't really support it and will also drop references to it.  Plus the last homebrew kit we used to build the psp port used an old version of gcc which we had trouble supporting.

**Comment by ericoporto** [comment]
So in summary, removing psp and ms-dos mentions.

When necessary, should Android and iOS be added too? I have never tested iOS - lack of device, it's very expensive. Should it be mentioned by how it theoretically behaves? @sonneveld , have you built for iOS, perhaps using SDL?

**Comment by ivan-mogilko** [comment]
Wadjet Eye has released number of games on iOS. It worked at least before 3.4.1 when the compilation broke.

**Comment by ericoporto** [comment]
About removal of mentions of DOS and PSP, here are my findings. I will wait if there are any comments before proceeding for removal.

Mentions of DOS
- [Game.md **#setmultitaskingmode**](https://github.com/adventuregamestudio/ags-manual/wiki/Game#setmultitaskingmode)
  > Cross-Platform Support
  > 
  > Windows: Yes
  > **MS-DOS: No**
  > Linux: Yes
  > MacOS: Yes
- [Game.md **#runagsgame**](https://github.com/adventuregamestudio/ags-manual/wiki/Game#runagsgame)
  > ...speech.vox and so forth. This is a limitation of this command.
  >
  > NOTE: The game you run will be loaded at the same resolution and colour depth as the current game; if you mismatch colour depths some nasty results will occur.
  > 
  > NOTE: Make sure that the game you want to run has a filename of **8 characters or less, or this command will fail in the DOS engine**.
  > 
  > NOTE: The...
- [ListBox.md **#filldirlist**](https://github.com/adventuregamestudio/ags-manual/wiki/ListBox#filldirlist)
  > FILEMASK is a standard **DOS**/Windows search expression such as "*.dat" or "data*.*"
- [Multimedia.md **#cdaudio**](https://github.com/adventuregamestudio/ags-manual/wiki/Multimedia#cdaudio)
  > Cross-Platform Support
  > 
  > Windows: Yes, but supports 1 CD-ROM drive only
  > **MS-DOS: Yes, if CD-ROM device driver loaded**
  > Linux: Yes, but supports 1 CD-ROM drive only
  > MacOS: No
- [Multimedia.md **#playvideo**](https://github.com/adventuregamestudio/ags-manual/wiki/Multimedia#playvideo)
  > Cross-Platform Support
  > 
  > Windows: Yes
  > **MS-DOS: No**
  > Linux: No
  > MacOS: Yes
- [Region.md **#lightlevel**](https://github.com/adventuregamestudio/ags-manual/wiki/Region#lightlevel)
  > The light level is from -100 to 100. This is different from the editor, which takes values from 0 to 200. Subtract 100 from the value you would use in the editor when calling this function. The reason for this discrepancy is legacy reasons from **the DOS editor** days.
- [System.md **#hardwareacceleration**](https://github.com/adventuregamestudio/ags-manual/wiki/System#hardwareacceleration)
  > Cross-Platform Support
  > 
  > Windows: Direct3D driver
  > **MS-DOS: No**
  > Linux: No
  > MacOS: No
- [System.md **#operatingsystem**](https://github.com/adventuregamestudio/ags-manual/wiki/System#operatingsystem)
  > **`eOSDOS`**
  > `eOSWindows`
  > `eOSLinux`
  > ...
- [System.md **#supportsgammacontrol**](https://github.com/adventuregamestudio/ags-manual/wiki/System#supportsgammacontrol)
  > Cross-Platform Support
  > 
  > Windows: Full-screen only
  > **MS-DOS: No**
  > Linux: No
  > MacOS: No

Mentions of PSP
- [System.md **#operatingsystem**](https://github.com/adventuregamestudio/ags-manual/wiki/System#operatingsystem)
  > ...
  > `eOSAndroid`
  > `eOSiOS`
  > **`eOSPSP`**

**Comment by ivan-mogilko** [comment]
> * FILEMASK is a standard **DOS**/Windows search expression such as "_.dat" or "data_.*"

This is probably not a valid thing to say today because these are also valid on other systems, at least linux. Maybe remove system names and simply say "file search expression". Maybe even give a link to wildcard search article in the web?

> * The light level is from -100 to 100. This is different from the editor, which takes values from 0 to 200. Subtract 100 from the value you would use in the editor when calling this function. The reason for this discrepancy is legacy reasons from **the DOS editor** days.

This may be left perhaps since it is simply explaining a legacy design.

**Comment by morganwillcock** [comment]
I  think this probably needs to be more specific.

- is case-sensitivity relevant?
- can you use any wildcard characters other than an asterisk?
  - if so, how do you escape them for a literal match?
('?' and '*' may be valid for filenames on systems that aren't Windows)

Note: the manual build is stripping out some asterisks here, which is why '.dat' is described as a search expression, but isn't one.

**Comment by sonneveld** [comment]
> When necessary, should Android and iOS be added too? I have never tested iOS - lack of device, it's very expensive. Should it be mentioned by how it theoretically behaves? @sonneveld , have you built for iOS, perhaps using SDL?

I think the intent is for AGS to support iOS and Android (even if there are no proper releases).  I plan to support iOS and Android via SDL (as SDL supports both) but I haven't investigated yet.

**Comment by ericoporto** [comment]
> Note: the manual build is stripping out some asterisks here, which is why '.dat' is described as a search expression, but isn't one.

This is solved by ``` `.dat` ``` I believe, which will properly escape and made it written as code.

**Comment by ericoporto** [comment]
- [Multimedia.md **#playvideo**](https://github.com/adventuregamestudio/ags-manual/wiki/Multimedia#playvideo)
  > Cross-Platform Support
  > 
  > Windows: Yes
  > **MS-DOS: No**
  > Linux: No
  > MacOS: Yes
  - Removed here: [af218d9](https://github.com/adventuregamestudio/ags-manual/wiki/_compare/c295d8f9f4b2d0038a8987bc0093f81f3424fd23...af218d9b3e09943004009ca4484b500adecc3935)

**Comment by ericoporto** [comment]
> Note: the manual build is stripping out some asterisks here, which is why '.dat' is described as a search expression, but isn't one.

This is solved by ``` `.dat` ``` I believe, which will properly escape and made it written as code.

Here is a list of modifications following comments here.

Mentions of DOS
- [Game.md **#setmultitaskingmode**](https://github.com/adventuregamestudio/ags-manual/wiki/Game#setmultitaskingmode)
  > Cross-Platform Support
  > 
  > Windows: Yes
  > **MS-DOS: No**
  > Linux: Yes
  > MacOS: Yes
  - Removed here: [697a8a0](https://github.com/adventuregamestudio/ags-manual/wiki/_compare/af218d9b3e09943004009ca4484b500adecc3935...697a8a0d586959b1cd5ee712f25fc6dc7673a4f9)

- [Game.md **#runagsgame**](https://github.com/adventuregamestudio/ags-manual/wiki/Game#runagsgame)
  > ...speech.vox and so forth. This is a limitation of this command.
  >
  > NOTE: The game you run will be loaded at the same resolution and colour depth as the current game; if you mismatch colour depths some nasty results will occur.
  > 
  > NOTE: Make sure that the game you want to run has a filename of **8 characters or less, or this command will fail in the DOS engine**.
  > 
  > NOTE: The...
  - Removed here: [f580d5a](https://github.com/adventuregamestudio/ags-manual/wiki/_compare/697a8a0d586959b1cd5ee712f25fc6dc7673a4f9...f580d5a363591afd754cdce469fcbb1cee369eb8)
- [System.md **#hardwareacceleration**](https://github.com/adventuregamestudio/ags-manual/wiki/System#hardwareacceleration)
  > Cross-Platform Support
  > 
  > Windows: Direct3D driver
  > **MS-DOS: No**
  > Linux: No
  > MacOS: No
  - Removed here: [802b2fe](https://github.com/adventuregamestudio/ags-manual/wiki/_compare/f580d5a363591afd754cdce469fcbb1cee369eb8...802b2fe3c7c448deb049187b6d4c64e02345f87a)

- [Multimedia.md **#playvideo**](https://github.com/adventuregamestudio/ags-manual/wiki/Multimedia#playvideo)
  > Cross-Platform Support
  > 
  > Windows: Yes
  > **MS-DOS: No**
  > Linux: No
  > MacOS: Yes
  - Removed here: [af218d9](https://github.com/adventuregamestudio/ags-manual/wiki/_compare/c295d8f9f4b2d0038a8987bc0093f81f3424fd23...af218d9b3e09943004009ca4484b500adecc3935)

- [System.md **#supportsgammacontrol**](https://github.com/adventuregamestudio/ags-manual/wiki/System#supportsgammacontrol)
  > Cross-Platform Support
  > 
  > Windows: Full-screen only
  > **MS-DOS: No**
  > Linux: No
  > MacOS: No
  - Removed here: [99e610b](https://github.com/adventuregamestudio/ags-manual/wiki/_compare/802b2fe3c7c448deb049187b6d4c64e02345f87a...99e610bc00990587cd67ebd01014ef795eff514d)

- [Multimedia.md **#cdaudio**](https://github.com/adventuregamestudio/ags-manual/wiki/Multimedia#cdaudio)
  > Cross-Platform Support
  > 
  > Windows: Yes, but supports 1 CD-ROM drive only
  > **MS-DOS: Yes, if CD-ROM device driver loaded**
  > Linux: Yes, but supports 1 CD-ROM drive only
  > MacOS: No
  - Removed here: [6935864](https://github.com/adventuregamestudio/ags-manual/wiki/_compare/99e610bc00990587cd67ebd01014ef795eff514d...69358648a71cb0c780c999c325d97b2715747be1)

Mentions still in for now:
Mentions of DOS
- [ListBox.md **#filldirlist**](https://github.com/adventuregamestudio/ags-manual/wiki/ListBox#filldirlist)
  > FILEMASK is a standard **DOS**/Windows search expression such as "*.dat" or "data*.*"

- [Region.md **#lightlevel**](https://github.com/adventuregamestudio/ags-manual/wiki/Region#lightlevel)
  > The light level is from -100 to 100. This is different from the editor, which takes values from 0 to 200. Subtract 100 from the value you would use in the editor when calling this function. The reason for this discrepancy is legacy reasons from **the DOS editor** days.
- [System.md **#operatingsystem**](https://github.com/adventuregamestudio/ags-manual/wiki/System#operatingsystem)
  > **`eOSDOS`**
  > `eOSWindows`
  > `eOSLinux`
  > ...

Mentions of PSP
- [System.md **#operatingsystem**](https://github.com/adventuregamestudio/ags-manual/wiki/System#operatingsystem)
  > ...
  > `eOSAndroid`
  > `eOSiOS`
  > **`eOSPSP`**

**Comment by selmiak** [comment]
what about adding the current supported systems to 

SystemRequirements.md

and listing the required specs for every system supported.

Also I think there might be people on the internet that still want to make an adventure game for PSP for example, those folks will be very interested in which version of AGS still supports PSP builts in some way. So at the bottom of that page maybe a "last AGS version that supports system X" list would be nice.

**Comment by ericoporto** [comment]
> what about adding the current supported systems to
> 
> SystemRequirements.md

I wouldn't list hardware specs required per system because I guess the person programming the game can make it more demmanding or not by simply doing more things per loop or using a plugin that is only compatible with systems that support X technology. But for software requirements I think it's fine.

The interesting part of this idea is to unite the infos per systems in a single document - possibly removing per system support across documents when possible. Maybe then the document should be a new document like CrossPlatform.md .

**Comment by ericoporto** [comment]
The mentions were mostly purged so I will close this.
