### ISSUE TITLE
Missing newer preprocessor commands

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags-manual#39]
e.g. `#region` and `#endregion` are not documented

**Comment by selmiak** [comment]
I'd say it has its place either under 

**Editor Reference > Other Features**
(This section describes AGS features that were not covered in the tutorial.)

or just under 

**Scripting**

the first one is more for editor windows, so scripting might be better suited, but there it easily gets lost and actually it has no effect on the script after all, but it helps with organizing the scripts (like the different editor windows do...).

**Comment by ericoporto** [comment]
Ok, I imagine the description would be: 

*Preprocessor region*

You can wrap a code between lines containing `#region` and `#endregion` to create a section used for code folding. In the AGS Editor you can use this to hide sections of your code you don't need to see by using the `+` button at the left side of the script editor.

**Comment by ivan-mogilko** [comment]
Perhaps **Scripting** > **Preprocessor keywords** ?

BTW, #ifver command is described in "Script language keywords" in "Version checking" paragraph.

**Comment by ericoporto** [comment]
Ok, created a page [Preprocessor.md](https://github.com/adventuregamestudio/ags-manual/wiki/Preprocessor) , and placed it under [ScriptingLanguage.md](https://github.com/adventuregamestudio/ags-manual/wiki/ScriptingLanguage). The page is still in initial state, I don't use much preprocessor entries... What is supported?

**Comment by ivan-mogilko** [comment]
https://github.com/adventuregamestudio/ags/blob/ags3/Editor/AGS.CScript.Compiler/Preprocessor.cs

Macro creation
* #define
* #undef

Test if macro is defined
* #ifdef,
* #ifndef

Test if is compiled by particular version of AGS (perhaps move from https://github.com/adventuregamestudio/ags-manual/wiki/ScriptKeywords#version-checking)
* #ifver
* #ifnver

User defined compile-time error (with message)
* #error

Regions
* #region
* #endregion

These do nothing, ignored legacy commands from pre-3 era. Still maybe mention them since they are valid keywords.

* #sectionstart
* #sectionend

**Comment by ericoporto** [comment]
I got a little confused with `#ifver` and `#ifnver`. They check for equal and above, and below, or only equal and not equal?

I copied the text from the referred topic to here:
https://github.com/adventuregamestudio/ags-manual/wiki/Preprocessor#ifver-version-checking

**Comment by ivan-mogilko** [comment]
#ifver means "at least version X"
#ifnver means "before version X"

**Comment by selmiak** [comment]
just wondering, can you enclose some ifs?

#ifver 2.72
...  #ifver 3.2.1
...   // do stuff for 3.2.1 and above
...  #endif
...  #ifnver 3.2.1
...  // do stuff for 3.2.0 and below but above 2.72
...  #endif
#endif
#ifnver 2.72
// do stuff for 2.71 and below
#endif

**Comment by ericoporto** [comment]
I have no idea, would need to test... I like to take a look on tween source when I am curious

https://github.com/edmundito/ags-tween/blob/master/Tween/Tween.ash
https://github.com/edmundito/ags-tween/blob/master/Tween/Tween.asc

Looks like for version checking it isn't needed to nest to accomplish what you want but from other ifdef checks, it looks like it's nestable .

**Comment by ivan-mogilko** [comment]
yes they are nestable.

**Comment by ericoporto** [comment]
We may eventually improve the preprocessor page, but for now it exists and has regions, so it should have corrected this issue. I will now close it.

**Comment by morganwillcock** [comment]
Would it be okay if I edit this page to take the inline code out of the headers? For purposes of indexing I'm processing header elements, but I've realised that I'm only getting partial text on this page.

**Comment by ericoporto** [comment]
Sure, no problem, just remove the backticks :)
