### ISSUE TITLE
Why is the Music and Sound Page called MusAndSound

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags-manual#40]
https://github.com/adventuregamestudio/ags-manual/wiki/MusAndSound

And will changing this break lots of links?

Is there a way to find out which pages link to a specific page?

**Comment by ericoporto** [comment]
There is a way to check for broken links

https://github.com/adventuregamestudio/ags-manual/blob/master/README.md#checking-wiki-links

You will have to download both the manual and the wiki to your computer to
do it though - I can do it later, but it isn't hard.

**Comment by morganwillcock** [comment]
I've renamed the page in wiki commit 21d61f2b8d12780c4b9d32dff9fc8bc3e7fc7d2c
