### ISSUE TITLE
Expand translation instructions

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags-manual#42]
There are additional options for translations that are only mentioned inside trs scripts:

<pre>
// AGS TRANSLATION SOURCE FILE
// Format is alternating lines with original game text and replacement
// text. If you don't want to translate a line, just leave the following
// line blank. Lines starting with '//' are comments - DO NOT translate
// them. Special characters such as [ and %%s symbolise things within the
// game, so should be left in an appropriate place in the message.
// 
// ** Translation settings are below
// ** Leave them as "DEFAULT" to use the game settings
// The normal font to use - DEFAULT or font number
//#NormalFont=DEFAULT
// The speech font to use - DEFAULT or font number
//#SpeechFont=DEFAULT
// Text direction - DEFAULT, LEFT or RIGHT
//#TextDirection=DEFAULT
//  
// ** REMEMBER, WRITE YOUR TRANSLATION IN THE EMPTY LINES, DO
// ** NOT CHANGE THE EXISTING TEXT.
</pre>

Notably:
* Using comments
* Setting up font replacement
* Dealing with formatted strings

This info should be useful for both game developers and translators (who are not necessarily experts in  AGS)

**Comment by ivan-mogilko** [comment]
Updated topic.
