### ISSUE TITLE
Undocumented nesting PauseGame behavior

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#44]
This is very important, but not documented for some reason.

PauseGame/UnPauseGame actually do not work as a simple on/off state, but as a counter.

This means that calling PauseGame two times will increase pause counter twice. If you call UnPauseGame only once after, the game will remain paused.

Couple of tricks:

1. Make sure that game is paused only once:
`if (!IsGamePaused()) PauseGame();`

2. Make sure that game gets unpaused always:
`while (IsGamePaused()) UnPauseGame();`

**Comment by tzachshabtay** [comment]
Is there a good reason for this behavior?

**Comment by ericoporto** [comment]
https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/global_game.cpp#L150

![image](https://user-images.githubusercontent.com/2244442/53928751-fe145580-4069-11e9-8284-9fc396494653.png)

@ivan-mogilko I know the manual says it returns true or false, but it's actually an int.

**Comment by ivan-mogilko** [comment]
A lot of old AGS functions are int.

**Comment by ericoporto** [comment]
@ivan-mogilko added the info on the docs below.
[Changed Game.md to include info on UnPauseGame and PauseGame being counters - 637b130](https://github.com/adventuregamestudio/ags-manual/wiki/_compare/0f354001bb1d4e9378028768a8794ec1665ba3f1...637b130c5840d40fd500b9c2cdb5164e83078657)
