### ISSUE TITLE
Translating the manual

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags-manual#45]
would it be possible to have the manual editable for every in different languages?

Slowly but steady we could even translate the manual, but would this be managable from a file system point of view?

Would this also work within AGS with the F1 help?

**Comment by ericoporto** [comment]
I am not sure, we still need to make pages for the interfaces, and diluting the little amount of people we have doesn't sound like a good idea. 

Anyone can get the markdown files from the wiki and translating it in your own pc and build the things locally - if one wants a personalized chm. 

I think this would be too hard to maintain in sync - and the community was against moving the docs to be online only hosted, where it would at least be easy for anyone to update and fix translation after release.

In sum, technically, it can be done: just make the toplevel page a language selection and create a folder with each language short names, throw each markdowns in it's places. But require many humans to maintain each translation.

**Comment by selmiak** [comment]
I think this can be closed or should stay here as a reminder that it is waaaaay over our capacties atm.
erio's answer is good....
