### ISSUE TITLE
Web Search should be case insensitive

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#51]

**Comment by morganwillcock** [comment]
To elaborate a little; The keyword table for each page is case-sensitive (to offer the possibility of the search being case-sensitive or case-insensitive). It would be fairly easy to force the table generation and/or the search term to a consistent case, but it is fairly important to keep a case-insensitive option:

<pre>Object* myobj = object[0];</pre>

The current search system was just a basic starting point, but if sticking with it I'd probably try to put a checkbox by the input field that toggled case-sensitivity on and off.

**Comment by ericoporto** [comment]
While I understand your reasoning, I still think by default the search should be case insensitive.

**Comment by morganwillcock** [comment]
I wasn't suggestion the search shouldn't case sensitive, just that achieving this by making use of the existing search function and modifying the underlying data would lose some context about the result. But what you are suggesting is the opposite of that, so that's fine.

**Comment by ericoporto** [comment]
I think you misread me, I understood the case for ambiguities of names in AGS, you suggested a check box of case sensitivity, I agree it's a good idea. I was only arguing it be unchecked by default and offered a different take without check box, just to reflect on how the interface should look.

**Comment by ericoporto** [comment]
I think #57 is the bigger issue to be discussed, so I am closing this.
