### ISSUE TITLE
Web version needs better styling and layout

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags-manual#55]
The existing web version of the manual is using [Milligram](https://milligram.io/), mainly because it was small, available on a CDN (no need to compile anything), and the default style for code blocks seemed pretty good. The only customisation was to implement the top bar, change the colour from purple to blue, and add and red and green highlight for search results.

The only layout feature used is the grid system, which splits the document links on the left from the document content on the right. It collapses at a pre-configured size to work on mobile. The classes are defined in the HTML5 Pandoc template, which optionally ignores the left-hand cell for pages which use the full width (e.g. genindex.html which render its own A-Z links).

Layout is slightly hampered by using the built-in Pandoc TOC in the left cell, so implementing a a custom TOC as part of the page render may help with spacing, although ideally we wouldn't want CSS classes being hard-coded in custom Pandoc writers.

**Comment by selmiak** [comment]
So can we change the CSS?

some suggestions for custom css:

.search-match {
    background: #d7e9fb;
    padding:5px;
}

.search-nomatch {
    background: #e24a4a;
    padding: 5px;
    color: #fff5f5;
}

both exist in main.css and I added the padding and changed some colors. Who says positive results have to be green on blue cup territory?!

The next one doesn't even exist but would fit into main.css

#search_input {
    padding:5px;
}

**Comment by selmiak** [comment]
looks good and can be closed

**Comment by morganwillcock** [comment]
Perhaps a good question to ask is:
"Does it look as good as a similar project's Sphinx build?"

https://www.renpy.org/doc/html/

**Comment by ericoporto** [comment]
I recently found the [docsify](https://docsify.js.org/#/) project, which produces beautiful websites from markdown files. Of course, even though it's promissing and a ton of people are using, it has a ton of problems too. I really liked it's website design though, which is why I am linking here.

**Comment by morganwillcock** [comment]
> One thing I think it's important to have as the things that are anchors as links themselves. Currently I need to manually add #this-anchor-name on top, to pass a topic to someone looking help in a page that has a ton of content.

I gave the anchor links a try:
https://github.com/morganwillcock/ags-manual/commit/e19049080e7a3bf3fa99218d4b478c76180cf76d

Whether this is the best way to do it, I'm not sure. Adding the element isn't a problem, but applying a layout to it seems quite tricky. I didn't really want to start setting custom CSS classes within the Pandoc writers or filters, but since you need something to target to format for styling I can't think of a safer way at the moment (maybe it is better to target the 'level' class that is already there to avoid anything custom, or see if layout is easier if the anchor is to the left of heading). Unfortunately you cannot just modify the headers themselves because these changes are then picked up by the automatic table of contents (what shows on the left of the page).

**Comment by ericoporto** [comment]
Hey, working great. I really like the current style and how blazingly fast the manual loads. :)

Do you guys have ideas for the manual first page?

**Comment by morganwillcock** [comment]
For styling, the Markdown preview that I've somehow acquired in VSCode looks quite good. Maybe we could borrow the CSS from here.

![camera](https://user-images.githubusercontent.com/14958747/66608123-aca6e880-ebad-11e9-934f-fdf3e8110946.png)

**Comment by ericoporto** [comment]
The CSS and styling of the manual has changed already. I think this can be closed and new issues with styling can be tackled in... Well, new issues.
