### ISSUE TITLE
Broken external links

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags-manual#6]
Sphinx has a built in link test for external URLs. It would be good to run this as part of the deployment, but at the moment it is encountering broken links:

<pre>make linkcheck | egrep "\(line\s*[0-9]+\)\s* [^-]"

(line   14) ok        http://www.adventuregamestudio.co.uk/forums/index.php?action=search2
(line   14) broken    https://www.google.com.br/search?q=site%3Ahttp%3A%2F%2Fwww.adventuregamestudio.co.uk%2Fforums - 503 Server Error: Service Unavailable for url: https://www.google.com/sorry/index?continue=https://www.google.com.br/search%3Fq%3Dsite%253Ahttp%253A%252F%252Fwww.adventuregamestudio.co.uk%252Fforums&q=EgRYkB9UGO3J-NoFIhkA8aeDS0n5EsSLh1HAC2iOGwhikR7iRmgxMgFy
(line    9) redirect  http://www.opensource.org/licenses/artistic-license-2.0.php - permanently to https://opensource.org/licenses/artistic-license-2.0.php
(line   54) redirect  http://www.opensource.org/licenses/artistic-license-2.0.php - permanently to https://opensource.org/licenses/artistic-license-2.0.php
(line   11) redirect  http://www.opensource.org/licenses/artistic-license-2.0.php - permanently to https://opensource.org/licenses/artistic-license-2.0.php
(line 1045) broken    http://www.adventuregamestudio.co.uk/fonts - 404 Client Error: Not Found for url: http://www.adventuregamestudio.co.uk/fonts
(line 1042) redirect  http://scigraphicstudio.cjb.net - permanently to https://www.cjb.net/
(line    1) ok        https://www.youtube.com/view_play_list?p=21DB402CB4DAEAEF
(line  115) broken    http://www.adventuregamestudio.co.uk/fonts - 404 Client Error: Not Found for url: http://www.adventuregamestudio.co.uk/fonts
(line  110) broken    http://www.tdrdesign.net/downloads/fontedit.exe - ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
make: *** [linkcheck] Error 1</pre>

(the grep is to suppress the 'local' links as I couldn't find any config options for the linkcheck builder)

**Comment by ericoporto** [comment]
I pushed some fixes that could have fixed the broken links.

**Comment by morganwillcock** [comment]
<pre>make linkcheck | egrep "\(line\s*[0-9]+\)\s* [^-]"

(line   14) ok        http://www.adventuregamestudio.co.uk/forums/index.php?action=search2
(line    9) redirect  http://www.opensource.org/licenses/artistic-license-2.0.php - permanently to https://opensource.org/licenses/artistic-license-2.0.php
(line   54) redirect  http://www.opensource.org/licenses/artistic-license-2.0.php - permanently to https://opensource.org/licenses/artistic-license-2.0.php
(line   11) redirect  http://www.opensource.org/licenses/artistic-license-2.0.php - permanently to https://opensource.org/licenses/artistic-license-2.0.php
(line 1045) ok        http://www.adventuregamestudio.co.uk/site/ags/sci_fonts/
(line 1042) redirect  http://scigraphicstudio.cjb.net - permanently to https://www.cjb.net/
(line    1) ok        https://www.youtube.com/view_play_list?p=21DB402CB4DAEAEF
(line  110) ok        http://www.adventuregamestudio.co.uk/forums/index.php?topic=23521.0</pre>
