### ISSUE TITLE
Explaining breaking saves and ways work around that

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags-manual#62]
We need a page explaining what breaks saved games, and possible solutions around this.

Besides known ideas, couple of more things I figured out recently.

* If you must change room A1 contents but do not want to break saves at all costs: create a duplicate room A2 with a new number and teleport player there if they restore game saved in A1.
(not very convenient, but may work as a last resort).
* Something I realized recently: any managed object is not restricted to change on its own because its full contents are read from the save. This allows to use objects such as dynamic arrays to store important variables. Upon loading an old save you just need to test a length or other kind of "version" of that array and resize it (create new one, copy old contents, fill in rest with default values, replace pointer variable).
* AGS 3.5.0 adds a new variant of above: use Dictionary. It's easy to extend and easy to check which variables (keys) it contains, so may be used as a universal global storage for story variables that's easy to extend between game versions.

**Comment by ivan-mogilko** [comment]
Very dumb example of dynamic array solution

<pre>
#define GAME_VER_001_LENGTH 10
#define GAME_VER_002_LENGTH 20

int MyVarVersion;
int MyVariables[];

function game_start()
{
    MyVarVersion = 2;
    MyVariables = new int[GAME_VER_002_LENGTH ];
}

function on_event(EventType evt, int data)
{
     if (evt == eEventRestoreGame)
     {
            if (MyVarVersion == 1)
            {
                 // this is old save!!
                int new_vars[] = new int[GAME_VER_002_LENGTH ];
                for (int i = 0; i < GAME_VER_001_LENGTH; i++ )
                     new_vars[i] = MyVariables[i]; // copy old stuff
                // set default values for the rest
                // replace pointer
                MyVariables = new_vars;
                MyVarVersion  = 2;
            }
     }
}
</pre>

**Comment by ivan-mogilko** [comment]
Wrote an article: https://github.com/adventuregamestudio/ags-manual/wiki/GameSavesCompatibility
May be amended from there.
