### ISSUE TITLE
Add Dictionary manual entries

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#73]
I have written a sketch on [Dictionary.md](https://github.com/adventuregamestudio/ags-manual/wiki/Dictionary).

I think it belongs to script API but the manual also has a script language section.

**Comment by ivan-mogilko** [comment]
This really should be part of larger task "update manual to 3.5.0 API".

It definitely belongs to script API, script language section is dedicated to scripting syntax,

**Comment by ericoporto** [comment]
Do you prefer an issue with a tasklist or multiple issues grouped under a milestone? GitHub doesn't support Epics like Jira.

**Comment by ericoporto** [comment]
This looks fine for me now.
