### ISSUE TITLE
New entry on Upgrading from Previous Version for AGS 3.5.0

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#78]
Edit: As suggested by @ivan-mogilko , the example to follow is the last major version, AGS 3.4.0, where the entry was [**UpgradeTo34.md**](https://github.com/adventuregamestudio/ags-manual/wiki/UpgradeTo34). 

[AGS 3.5.0 Forum Thread](https://www.adventuregamestudio.co.uk/forums/index.php?topic=57133.0)

A new entry should be made. It's interesting to note what is in and what is gone, and maybe offer some comparisons like the table below

Old command | New command(s)
-- | --
SetViewport(x, y); | Game.Camera.SetAt(x, y);
ReleaseViewport(); | Game.Camera.AutoTracking = true;
GetViewportX(); | Game.Camera.X;
GetViewportY(); | Game.Camera.Y;

(from [Script API](https://www.adventuregamestudio.co.uk/forums/index.php?topic=57133.0))
<details><summary> here are changes to Script API for reference </summary>
<p>
 - Introduced new managed struct Point describing (x,y) coordinates.
 - Introduced StringCompareStyle enum and replaced "caseSensitive" argument in String functions with argument of StringCompareStyle type.
 - Implemented Dictionary and Set script classes supporting storage and lookup of strings and key/value pairs in sorted or unsorted way. Added SortStyle enum for use with them.
 - Implemented Viewport and Camera script classes which control how room is displayed on screen.
 - Implemented Screen struct with a number of static functions and properties, which notably features references to the existing Viewports. Deprecated System's ScreenWidth, ScreenHeight, ViewportWidth and ViewportHeight in favor of Screen's properties.
 - Added Game.Camera, Game.Cameras and Game.CameraCount properties.
 - All functions that find room objects under screen coordinates are now being clipped by the viewport (fail if there's no room viewport at these coordinates).
   This refers to: GetLocationName, GetLocationType, IsInteractionAvailable, Room.ProcessClick, GetWalkableAreaAt and all of the GetAtScreenXY functions (and corresponding deprecated functions).
 - Added Character.GetAtRoomXY, Hotspot.GetAtRoomXY, Object.GetAtRoomXY, Region.GetAtScreenXY, replaced GetWalkableAreaAt with GetWalkableAreaAtScreen and added GetWalkableAreaAtRoom.
 - Replaced Alignment enum with a new one which has eight values from TopLeft to BottomRight.
 - Renamed old Alignment enum to HorizontalAlignment, intended for parameters that are only allowed to be Left, Center or Right.
 - Added new script class TextWindowGUI, which extends GUI class and is meant to access text-window specific properties: TextColor and TextPadding.
 - Added new properties to GUI class: AsTextWindow (readonly), BackgroundColor, BorderColor, PopupStyle (readonly), PopupYPos.
 - Added Button.TextAlignment and Label.TextAlignment.
 - Added missing properties for ListBox: SelectedBackColor, SelectedTextColor, TextAlignment, TextColor.
 - Replaced ListBox.HideBorder and HideArrows with ShowBorder and ShowArrows.
 - Added TextBox.ShowBorder.
 - Added Game.PlayVoiceClip() for playing non-blocking voice.
 - Added SkipCutscene() and eSkipScriptOnly cutscene mode.
 - Allowed to change Mouse.ControlEnabled property value at runtime.
 - Added Game.SimulateKeyPress().
 - Try to create all subdirectories when calling File.Open() for writing, DynamicSprite.SaveToFile() and Game.SetSaveGameDirectory().
 - Deprecated DrawingSurface.UseHighResCoordinates. Also, assigning it will be ignored if game's "Allow relative asset resolutions" option is disabled.
</p>
</details>

**Comment by ivan-mogilko** [comment]
"Upgrading" topics usually gave two sorts of notes:
* breaking changes and workarounds to make old api work (if possible);
* notable major changes

**Comment by ericoporto** [comment]
True, I changed the reading suggestion above. I imagine the breaking changes that are a must is the new camera and viewport system, also the move of screen size from System to Screen object. The Room Editor and the Sprite importer are two good additions, but the Room Editor perhaps changes the workflow more, would it make the notability to be mentioned?

**Comment by ericoporto** [comment]
The new entry exists as [UpgradeTo350.md](https://github.com/adventuregamestudio/ags-manual/wiki/UpgradeTo350) .

**Comment by ericoporto** [comment]
Written and Moved to https://github.com/adventuregamestudio/ags-manual/wiki/UpgradeTo35
