### ISSUE TITLE
Add to README a reminder on Win10 and internet downloaded chm

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#84]
I need to add a line on the README explaining that a chm downloaded from the web may need to be marked in it's file properties to be able to read. Failing to do so results in blank file, on Windows 10.

**Comment by morganwillcock** [comment]
It isn't a simple thing to explain, but I've previously written some things here:
https://www.adventuregamestudio.co.uk/wiki/Prevent_AGS_from_triggering_antiviruses
(ignore the page title, I was correcting information which was pre-existing)

It isn't limited to Windows 10, certain Windows programs will set or maintain a flag that represents a Security Zone, and the HTML rendering engine used by the CHM viewer checks for it.

**Comment by ericoporto** [comment]
Because the Wiki doesn't work for me unless I am incognito, I am going to paste current text here

>## Introduction
> With the move to a more open source style of development for the AGS engine, game developers may use AGS builds that don't correspond to an official release. These are usually downloaded and extracted manually rather than installed with an installer and this can cause some problems with Windows security settings. Specifically, attempts to access the help file (ags-help.chm) from inside or outside the AGS editor may be blocked.
>
> This is caused by something called "alternate data streams".
>
>##What are "alternate data streams"?
> When a file is stored on a computer by the Operating System it's written in a particular way. In order to read a file back there is a need to know where it begins and ends on the disk, so a File System is used to store data. On Windows the most popular File System is NTFS which supports the use of alternate data streams. Normally the contents of a file will be saved into the NTFS $DATA attribute in the default stream but it is also possible to specify an alternate stream name and store data in a different location within the same file. One common alternate stream name is named "Zone.Identifier" which is used to indicate the Windows Security Zone that a file originates from. This is commonly used to indicate that a file originates from another computer, the origin being indicated by a zone number. The zone numbers are defined by Zone Security settings in Internet Options.
>
> It's typically up to individual web browsers and download utilities running on Windows as to whether they write to the "Zone.Identifier" stream when a file is downloaded, and equally any application could choose to check the "Zone.Identifier" stream of a file when it is being opened. The help file viewer is one such application and will, by default, refuse to open a file if the "Zone.Identifier" indicates it originated from a different computer (i.e. it is potentially unsafe).
>
> When looking at a file's properties, if a restrictive zone number is present in the "Zone.Identifier" stream the file will be listed as "blocked". Choosing to unblock the file will re-write the "Zone.Identifier" stream to indicate the file should not longer be restricted (i.e. programs shouldn't be able to identify the origin of the file
>
>## How do I clean my AGS editor files of "alternate data streams"?
> Usually it's just the single "Zone.Indentifier" alternate stream on the help file that causes a problem.
>
> - Right click the ags-help.chm file in Windows Explorer and press the unblock button.
> If the unblock button doesn't work this is usually because the AGS folder has been located somewhere where the user attempting to unblock does not have write permission (if this is the case it's likely that the user extracting the AGS Editor would have encountered a UAC prompt when extracting to the AGS Editor files and approved the process to run with elevated permissions). The easiest solution is to run the Windows program "streams.exe" with elevated permissions. It can be download from here.
>
> - Download the zip file and extract it to any temporary directory, e.g. the Desktop.
> - Open a Windows Command prompt using "run-as administrator"
> - In the command prompt, change to to directory where the files were extracted:
> `cd "<EXTRACTION FOLDER>"`
> (you need to replace "<EXTRACTION FOLDER>" with the path to where streams.exe was extracted. For example "C:\Users\MyAccount\Desktop\Streams")
>
> (use double quotes when the path contains spaces)
>
> Run the following command to recursively remove any alternate data streams:
>
> `streams.exe -s -d "<AGS EDITOR FOLDER>"`
> (you need to replace "<AGS EDITOR FOLDER>" with the path to where the AGS Editor folder was extracted. For example "C:\Users\MyAccount\My Documents\AGS Builds\ags_3.4.12")
>
> (use double quotes when the path contains spaces)
> 
> 
> An alternate solution is to move the AGS Editor files to a location that doesn't use an NTFS file system, and then move the files back to the computer again. Most USB memory sticks will be formatted with the FAT32 File System instead of NTFS. FAT32 does not support alternate data streams so they cannot exist on the memory stick.

**Comment by ericoporto** [comment]
I am curious of how to name this. Fixing AGS Windows Security Zone maybe? And the file being `FixingAGSWindowsSecurityZone.md` under a trouble shooting area, and simplified explanation for manual only in both the README and the FAQ. 

I still feel the items on the index are not good, like, the stuff under Other Features is kind of hidden.

**Comment by morganwillcock** [comment]
It should probably go into an 'installation' section which says how to install the program, and this should probably only be interested in discussing files which make up a release.

- It isn't an issue if you use the InnoSetup installer because when the files are unpacked the files won't be present.

- It is a problem where someone downloads the Editor as a zip file, because the security zone specified on the archive is added to all extracted files by the unzipping process that is built into Windows. So the important part is to remove the zone identifier before you extract it or use an unzipping tool that isn't interested in the identifier.

- It is a confusing problem when someone extracts the Editor zip file to somewhere where an unelevated process cannot write such as "C:\Program Files" (Windows will helpfully prompt to elevate the copy process if you do this manually). This means that removing the zone identifier will need to be done by a process that is elevated, because otherwise you don't have permission to modify the files. The Editor tries to remove the zone identifier when the file is opened by pressing F1, but this will fail unless the Editor is running as an elevated process (which isn't an advisable thing to do, except to fix this specific problem).

**Comment by ericoporto** [comment]
So what I get is, we need to add a `install` h2 here on [introduction](https://github.com/adventuregamestudio/ags-manual/wiki/Introduction), that tells to use the installer, no need to mention it comes from InnoSetup I guess, just it's a installer and where to get it. It should also have a section on getting from zip, maybe also hinting Betas usually only comes in zip form. There a very small and short item to deal with security zone.

And on a different md file like InstallationTroubleshooting add more details on the problems you stated above, and the contents of the security zone full explanation. This InstallationTroubleshooting would then be linked by the introduction too.

**Comment by ericoporto** [comment]
Só, apparently this problem of the security zone on Windows blocking a file downloaded from the internet happens not only with the manual, but also [plugins downloaded from the internet](https://www.adventuregamestudio.co.uk/forums/index.php?topic=45622.msg636610764#msg636610764). So I think it's easier to add this more general entry and then point in the needed places to this entry (the README, the AGS installation, and the area related to plugin installation).

**Comment by ericoporto** [comment]
I created the entry [TroubleshootingWindowsZoneID.md](https://github.com/adventuregamestudio/ags-manual/wiki/TroubleshootingWindowsZoneID) and for now the only link to it is the plugin installation entry. I just roughly messed with the introduction to account for the plugin case too.
