### ISSUE TITLE
Contents on generated chm is not complete

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#9]
![image](https://user-images.githubusercontent.com/2244442/43691525-3ba29f06-98f4-11e8-8462-3ef36f581705.png)

On the left column, Room Editor and GUI Editor can be expanded. Other files can't be expanded. Either all files should be able to expand or neither.

**Comment by morganwillcock** [comment]
I think this is built in behaviour for the format, as if I remove the index markers the result is the same. The original CHM manual does the same thing.

**Comment by ericoporto** [comment]
Ok, I found the problem but I don't have any ideas on the why. Apparently sphinx isn't generating a .hhc file! It should happen when sphinx says [writing TOC file...](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/htmlhelp.py) . Looking the code, I have NO IDEA why this is happening.

**Comment by ericoporto** [comment]
This is fixed after the switch from sphinx to pandoc with lua build, so this can be closed!
