### ISSUE TITLE
Explain Script API and language switches

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags-manual#91]
Must explain Script API and language switches clearly, either in one or two topics, somewhere around Script API/Scripting language sections of the manual.

**Comment by ericoporto** [comment]
Found detailed information on [Script API switching](https://github.com/adventuregamestudio/ags/wiki/A-quick-guide-to-Script-API#api-version-switch) so I think now I have a better understanding of how they work.

**Comment by ericoporto** [comment]
This is shortly explained in the Script API section, but it needs to be removed from there and get it's own page.

**Comment by ivan-mogilko** [comment]
Added https://github.com/adventuregamestudio/ags-manual/wiki/ScriptAPIOverview
