### ISSUE TITLE
Intro/contents page does not exist in the CHM contents

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#92]
The first page you see when open CHM is the intro/contents page, but there's no way to return to it after you switch to other page (except for clicking Back button).

**Comment by ericoporto** [comment]
The AGS Help viewer has no home button, so either it needs options to have a home button or the template has to be modified to include a home button.

![20190924_161606](https://user-images.githubusercontent.com/2244442/65543113-dfcb5580-dee6-11e9-8162-8f5ee612437b.jpg)

**Comment by ericoporto** [comment]
The manual should have a home button now. Hitting the home button should take you to the intro/contents page.
