### ISSUE TITLE
Index collisions for non-script pages

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags-manual#98]
It looks fairly easy to cause an index collision by having some headings with the same names, which also means that items like Editor properties are difficult to index (since properties like 'name' will be defined in multiple pages).

So this probably needs some page design convention to try and avoid collisions, or a reference to the page title in the index entry, or some kind of reverse lookup for the index.

On a sort of related note, if there is a heading that just says "Conclusions" you probably don't want that indexed at all.

**Comment by ivan-mogilko** [comment]
Would it be possible to switch to the manual index instead in the future?

Perhaps that would also allow to add extra alias keywords for existing topics when necessary.

**Comment by morganwillcock** [comment]
Yes, in theory the index can come from anywhere, so it could be metadata within the document, or metadata read from an external file, or a change of format (so switch to use reST).

...but at the moment I'll try to split the index data between script API and other content, and then try to add the reverse lookup, which I think will fix it.

**Comment by morganwillcock** [comment]
According to current checks there are no longer any name collisions.
